-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le : ven. 19 avr. 2024 à 20:03
-- Version du serveur : 10.11.6-MariaDB-0+deb12u1
-- Version de PHP : 8.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `lejar1343688`
--

-- --------------------------------------------------------

--
-- Structure de la table `plante`
--

CREATE TABLE `plante` (
  `idPlante` int(11) NOT NULL,
  `TypePlante` varchar(255) DEFAULT 'vivace',
  `NomPlante` varchar(255) DEFAULT NULL,
  `imgPlante` varchar(1000) DEFAULT 'img\\imgBDD\\',
  `CouleurFleur` varchar(255) DEFAULT NULL,
  `CouleurFeuillage` varchar(255) DEFAULT NULL,
  `Hauteur` float DEFAULT NULL,
  `Largeur` float DEFAULT NULL,
  `Floraison` varchar(255) DEFAULT NULL,
  `Floraison_s_` varchar(255) DEFAULT NULL,
  `TypeFeuillage` varchar(255) DEFAULT NULL,
  `Exposition` varchar(255) DEFAULT NULL,
  `TypeSol` varchar(255) DEFAULT NULL,
  `Silhouette` varchar(255) DEFAULT NULL,
  `Densite` varchar(255) DEFAULT NULL,
  `Rusticite` varchar(255) DEFAULT NULL,
  `Utilisation` varchar(1400) DEFAULT NULL,
  `Entretien` varchar(410) DEFAULT NULL,
  `PetitMoins` varchar(255) DEFAULT NULL,
  `PetitPlus` varchar(360) DEFAULT NULL,
  `NomLatin` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Déchargement des données de la table `plante`
--

INSERT INTO `plante` (`idPlante`, `TypePlante`, `NomPlante`, `imgPlante`, `CouleurFleur`, `CouleurFeuillage`, `Hauteur`, `Largeur`, `Floraison`, `Floraison_s_`, `TypeFeuillage`, `Exposition`, `TypeSol`, `Silhouette`, `Densite`, `Rusticite`, `Utilisation`, `Entretien`, `PetitMoins`, `PetitPlus`, `NomLatin`) VALUES
(7, 'arbre', 'Arbre aux quarante écus', 'img\\imgBDD\\ArbreAuxQuaranteEcus.png', 'jaunes', 'vert puis jaune', 10, 6, 'fin printemps', NULL, 'caduc', 'mi-ombre', 'bonne terre de jardin', 'érigée', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Canopée', 'ne nécessite aucune taille. Il faut plus de 10 ans avant qu\'un Ginkgo femelle produise des fruits, c\'est pourquoi les jeunes plants mâles ou femelles ne peuvent être différenciés sur des sujets jeunes', NULL, 'médicinale', 'Ginkgo biloba'),
(8, 'arbre', 'ALBIZIA Julibrissin (Arbre à soie)', 'img\\imgBDD\\ArbreASoie.png', 'rouges', 'vert puis jaune', 4, 4, 'été', NULL, 'caduc', 'soleil', 'bonne terre, sec', 'étalée', NULL, NULL, 'plantation en isolé. Fixateur d’azote. Fait partie de la pharmacopée de la médecine traditionnelle chinoise\r\nEntretien : protection du plant contre le froid pendant les deux premières années.', NULL, NULL, 'ramure étalée qui s\'élargit horizontalement au fil des ans. Cette forme d\'ombelle très particulière lui vaut d\'être un arbre recherché dans les jardins pour créer des espaces ombrés.', ''),
(17, 'arbre', 'Lilas de Perse, margousier (MELIA azedarach)', 'img\\imgBDD\\LilasDePerse.png', 'blanc lilas', 'vert puis jaune', 10, 4, 'mai-juin', NULL, 'caduc ', 'plein soleil, protégé du vent froid', 'frais mais tolère sécheresse bien drainé', 'touffe buissonnante', NULL, NULL, 'massif, talus, bordures. Les feuilles sont utilisées comme insecticide naturel, fraîches ou en purin (fruits aussi)', 'rabattre les hampes fanées pour obtenir une floraison remontante. Rabattre la touffe au plus tard au démarrage de la végétation au printemps.', NULL, NULL, ''),
(18, 'arbre', 'Saule jaune, saule doré = osier (SALIX alba \'Vitellina\')', 'img\\imgBDD\\SauleJaune.png', NULL, NULL, 20, 10, NULL, NULL, NULL, 'soleil', 'réussit aussi bien en sols frais que dans les sols secs et légers', NULL, NULL, NULL, 'si libre en isolé ou bordure d’une pièce d’eau dans les grands jardins. Sinon haie brise-vent si taillé. vannerie.\r\nmellifère, médicinal', 'ramasser et brûler les feuilles tombées si l\'arbre présente des taches noires (anthracnose) ou jaune orangé (rouille) durant sa végétation. Une fois toutes les feuilles tombées, traiter à la bouillie bordelaise. Tailler sévèrement la totalité des branchages pour former un têtard, sorte de moignon à partir duquel poussent les rameaux utilisés en vannerie.', NULL, NULL, ''),
(19, 'arbre', 'ALNUS cordata (Aulne de Corse)', 'img\\imgBDD\\AulneDeCorse.png', 'vert', NULL, 25, 6, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'frais à humide, tolère le sec en été', NULL, NULL, NULL, 'fixateur d’azote, sève comestible', NULL, NULL, 'sa forme conique apporte peu d’ombrage et en fait par conséquent un arbre de choix pour l’étage canopéen. La chute des feuilles en automne les disperse largement et favorise l’apport d’azote aux autres arbres et arbustes plus bas.', ''),
(20, 'arbre', 'GLEDITSIA triacanthos (Févier d\'Amérique)', 'img\\imgBDD\\FevierDAmerique.png', NULL, 'vert puis jaune', 20, 10, NULL, NULL, 'caduc', 'soleil', 'tous sauf acide', NULL, NULL, '-15°C', 'fixateur d’azote, isolé, bois de qualité, feuillage sert de fourrage', 'tailler avant reprise de la végétation pour maintenir beau port étalé, supprimer les drageons', NULL, NULL, ''),
(21, 'arbre', 'CERCIS siliquastrum (Arbre de Judée)', 'img\\imgBDD\\ArbreDeJudee.png', 'rose au printemps', 'vert', 5, 3, NULL, NULL, 'caduc', 'soleil', 'drainé, supporte calcaire', NULL, NULL, '- 14 °C', 'fixateur d’azote. Isolé, potager, massif, haie', 'taille de formation pour former la charpente et dégager le tronc', NULL, 'fleurs comestibles, mellifère, nectarifère', ''),
(22, 'arbuste', 'Chèvrefeuille d\'hiver parfumé (Lonicera fragrantissima)', 'img\\imgBDD\\LoniceraFragrantissima.png', 'blanches', 'vert', 2, 2, 'janvier-mars', NULL, 'semi-persistan', 'soleil, mi-ombre', 'tous, sec, calcaire', NULL, NULL, NULL, 'en haie, alignement, massif d’arbustes, isolé', 'tailler après la floraison pour assurer le renouvellement des jeunes pousses', NULL, 'très odorant et mellifère', ''),
(23, 'arbuste', 'Germandrée en arbre bleu (Teucrium fruticans)', 'img\\imgBDD\\TeucriumFruticans.png', 'bleu', 'vert', 2, 1, 'fin printemps, été', NULL, 'persistant', 'soleil, mi-ombre', 'drainé, sec', 'touffe érigée', NULL, NULL, 'en haie, alignement, massif d\'arbustes, isolé', 'tailler après la floraison pour assurer le renouvellement des jeunes pousses', NULL, 'mellifère', ''),
(24, 'arbuste', 'Abélia \'Edouard Goucher\' (Abelia)', 'img\\imgBDD\\Abelia.png', 'rose', 'vert foncé', 2, 2, 'été-automne', NULL, ' semi-persistant', 'soleil, mi-ombre', 'humifère et drainé', 'arrondie', NULL, NULL, 'haie, alignement, massif d\'arbustes, isolé, bac', 'raccourcir légèrement les branches après la floraison et effectuer une taille sévère des vieux bois tous les 4 ans .', NULL, 'mellifère', ''),
(25, 'arbuste', 'Abélia brillant (Abelia grandiflora)', 'img\\imgBDD\\AbeliaGrandiflora.png', 'blanche', 'vert', 2, 2, 'été, automne', NULL, ' semi-persistant', 'soleil, mi-ombre', 'humifère, drainé', 'arrondie', NULL, NULL, 'haie, alignement, massif d\'arbustes, isolé', 'raccourcir légèrement les branches après la floraison et effectuer une taille sévère des vieux bois tous les 4 ans .', NULL, 'mellifère', ''),
(26, 'arbuste', 'Abélia flagrant parfumé (Abelia mosanensis)', 'img\\imgBDD\\AbeliaMosanensis.png', 'blanc rosé', 'vert', 2, 2, 'été, automne', NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé', 'tailler après la floraison', NULL, 'odorant, mellifère', ''),
(27, 'arbuste', 'Seringat des jardins (Philadelphus coronarius)', 'img\\imgBDD\\PhiladelphusCoronarius.png', 'blanche', NULL, 3, NULL, 'mai-juillet', NULL, 'caduc', 'soleil', 'tous, riche', 'buissonnate', NULL, NULL, 'haie, isolé', 'pailler, arroser les 2 premières années, rabattre les longues tiges défleuries', NULL, 'parfum délicieux', ''),
(30, 'arbuste', 'Jasmin d\'hiver jaune (Jasminum nudiflorum)', 'img\\imgBDD\\JasminHiverJaune.png', 'jaune', 'vert', 3, 3, 'décembre-mars', NULL, 'caduc', 'soleil, mi-ombre', 'humifère', 'arbuste grimpant', NULL, NULL, 'palissé, talus', 'taille légère au printemps', NULL, NULL, ''),
(31, 'arbuste', 'Jasmin officinal (Jasminum officinale)', 'img\\imgBDD\\JasminOfficinal.png', 'blanche', 'vert', 2, NULL, NULL, NULL, 'semi-persistant', 'chaude et ensolleillée', 'humifère, bien drainé', 'arbuste grimpant', NULL, NULL, 'tonnelles, pergolas, bac', 'taille légère après la floraison', NULL, 'très parfumé, médicinale', ''),
(32, 'arbuste', 'BUDDLEIA davidii Nanho white (Arbre aux papillons)', 'img\\imgBDD\\ArbrePapillons.png', 'blanc', 'vert puis jaune', 2, 2, 'été', NULL, 'caduc', 'soleil', 'tous, calcaire, argileux', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé', 'tailler sévèrement en fin d’hiver', NULL, 'parfumé, mellifère, nectarifère', ''),
(33, 'arbuste', 'CEANOTHUS x delilianus \r\n\'Gloire de versailles\' (Céanothe, Lilas de Californie)', 'img\\imgBDD\\LilasCalifornie.png', 'bleue', 'vert puis jaune', 2, 1, 'juin-septembre', NULL, 'caduc', 'mi-ombre', 'sec, humifère, acide, non calcaire', 'érigée', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé', 'tailler en mars après les gelées. Protéger au Nord de la France.', NULL, 'mellifère', ''),
(34, 'arbuste', 'ELSHOLTZIA stauntoniin (Menthe en arbre)', 'img\\imgBDD\\MentheEnArbre.png', 'mauve', 'vert puis brun puis rouge', 2, 2, 'sept-novembre', NULL, 'caduc', 'mi-ombre', 'frais, drainé,  acide, calcaire', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé, bordure, pot', 'rustique. Se taille rabattu à 20-30 cm avant le printemps pour régénérer sa souche arbustive', NULL, 'nectarifère, mellifère, feuille odeur mentholée', ''),
(35, 'arbuste', 'VIBURNUM tinus (Laurier tin, viorne blanche)', 'img\\imgBDD\\LaurierTin.png', 'blanche', 'vert', 3, 3, 'novembre-avril', NULL, 'persistant', 'soleil, mi-ombre', 'sec, humifère, calcaire, argileux', 'buissonnante', NULL, NULL, 'haie, topiaire, alignement, massif d’arbustes, isolé', 'tailler après la floraison pour assurer le renouvellement des jeunes pousses', NULL, 'floraison odorante et mellifère. Fruits attractifs pour oiseaux.', ''),
(36, 'arbuste', 'HIBISCUS moscheutos \'Rubra\' (Hibiscus)', 'img\\imgBDD\\Hibiscus.png', 'rouge', 'vert', 2, 1, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'très humide, humifère, drainé', 'érigée', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé', 'tailler court en fin d\'hiver. A protéger dans les régions du Nord de la France', 'rustique jusqu’à -8°C', NULL, ''),
(37, 'arbuste', 'CLEMATIS \'Ernest Markham\' (Clématite italienne pourpre)', 'img\\imgBDD\\ClematiteItaliennePourpre.png', 'pourpre', 'vert', 10, 3, 'été, automne', NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé', 'grimpante', NULL, NULL, 'haie palissée, treillis, pergolas, bac', 'ombrer la souche, la Clématite doit avoir le pied à l\'ombre et la tête au soleil.', 'feuillage toxique ', NULL, ''),
(38, 'arbuste', 'CHOISYA ternata \'Moonglow\' (Oranger du Mexique)', 'img\\imgBDD\\OrangerDuMexique.png', 'blanche', 'jaune', 2, 2, 'mai-juin', NULL, 'persistant', 'soleil, mi-ombre', 'humifère, acide, argileux', 'arrondie', NULL, NULL, 'massif, haie, isolé, pot', 'tailler après la floraison', NULL, 'odorant, mellifère, remontant', ''),
(39, 'arbuste', 'NERIUM oleander \'Jannoch\' (Laurier rose)', 'img\\imgBDD\\LaurierRose.png', 'rouge vif, simple', 'vert', 3, 2, 'été', NULL, 'persistant', 'soleil', 'humifère, drainé, calcaire', 'arrondie', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé, bac', 'tailler en mars, après les gelées. Protéger dans les régions du Nord de la France. ', 'La sève et le feuillage sont toxiques.', NULL, ''),
(40, 'arbuste', 'Buddleia davidii \'Nanho Blue\' (Arbre aux papillons nain)', 'img\\imgBDD\\ArbrePapillonsNain.png', 'bleu lavande', 'vert', 2, 2, 'juin-sept', NULL, 'caduc', 'soleil (mi-ombre)', 'tous même pauvre', 'touffe buissonnante arrondie', NULL, NULL, 'isolé, haie libre, massif.\r\nmellifère, nectarifère, bouquet', 'tailler court au printemps', NULL, NULL, ''),
(41, 'arbuste', 'ELAEAGNUS x ebbingei (Eléagnus, chalef argenté)', 'img\\imgBDD\\Eleagnus.png', 'vert', NULL, 3, 2, NULL, NULL, 'persistant', 'soleil, mi-ombre', 'tous, sauf humides', 'touffe érigée', NULL, NULL, 'isolé, haie, massif. Mellifère, nectarifère, source de nourriture pour les oiseaux en hiver. Fruits comestibles. Fixateur d’azote', 'En isolé ou haie libre, tailler à la fin de l’hiver pour conserver un port compact. En haie, tailler au moins 2 fois par an. Supporte la taille sévère ', NULL, NULL, ''),
(43, 'arbuste', 'Buddleia jaune (Arbre aux papillons non invasif)', 'img\\imgBDD\\BuddleiaJaune.png', 'jaune', 'vert', 3, 2, 'juin-sept', NULL, 'caduc ou semi-persistant', 'soleil (mi-ombre)', 'tous même pauvre, drainé', 'touffe buissonnante arrondie', NULL, NULL, 'isolé, haie libre, massif. Mellifère, nectarifère, bouquet', 'tailler court au printemps', NULL, NULL, ''),
(44, 'arbuste', 'BUPLEURUM fruticosum (Buplèvre ligneux)', 'img\\imgBDD\\BuplevreLigneux.png', NULL, 'vert bleuté', 2, 2, NULL, NULL, 'persistant', 'soleil, mi-ombre', 'tous, supporte calcaire', 'touffe érigée', NULL, NULL, 'haie, massif d’arbustes', NULL, NULL, 'plante semencière pour revégétalisation de talus et espaces dégradés. Supporte bien la concurrence racinaire en lisière de bois de pins ou de chênes. Résiste aux embruns.', ''),
(46, 'arbuste', 'COTONEASTER franchetii (Cotonéaster de Franchet)', 'img\\imgBDD\\Cotoneaster.png', 'blanc rosé', 'gris-vert', 3, 4, 'mai-juin', NULL, 'persistant', 'soleil, mi-ombre', 'tous, frais, bien drainé', NULL, NULL, NULL, 'massif d’arbustes, haie, isolé', NULL, NULL, 'mellifère, supporte bien la taille, fruits décoratifs en automne-hiver', ''),
(47, 'arbuste', 'COTONEASTER horizontalis (Cotonéaster rampant)', 'img\\imgBDD\\CotoneasterRampant.png', 'blanc rosé', 'vert => rouge-orangé', 1, 2, 'mai-juin', NULL, 'caduc', 'soleil, mi-ombre', 'tous, frais, bien drainé', NULL, NULL, NULL, 'couvre-sol de talus ou rocailles, isolé', 'taille d’équilibre en mars', NULL, 'mellifère, supporte bien la taille, fruits décoratifs en automne-hiver appréciés des oiseaux', ''),
(48, 'arbuste', 'HYPERICUM \'Hidcote\' (Millepertuis)', 'img\\imgBDD\\Millepertuis.png', 'jaune', 'vert', 1, 2, 'juillet-octobre ', NULL, 'semi-persistant', 'soleil, mi-ombre dans le Sud', 'sec, drainé, pauvre\r\nSupporte le calcaire', NULL, NULL, '-15°C', 'massif d’arbustes, haies fleuries, talus', 'taille de mise en forme en fin d’hiver', NULL, 'mellifère, croissance rapide', ''),
(49, 'arbuste', 'HIBISCUS syriacus (Althéa)', 'img\\imgBDD\\Althea.png', 'rose', 'vert', 3, 2, 'juillet-octobre ', NULL, 'caduc', 'soleil', 'tous, drainé, fertile. Tolère le calcaire', NULL, NULL, '-15°C', 'haie, isolé, massif, pot', 'rabattre sévèrement en février-mars pour favoriser la floraison. ', NULL, 'croissance rapide', ''),
(50, 'arbuste', 'ROSA (Rosier grimpant)', 'img\\imgBDD\\RosierGrimpant.png', 'rose bicolore', 'vert brillant', 2, 2, 'mai aux gelées ', NULL, 'caduc', 'soleil', 'lourd, fertile, frais, drainé\r\nTolère un peu de calcaire', NULL, NULL, '-20°C', 'massif, isolé, treille, bouquet', 'au printemps rajeunir les charpentières en supprimant les plus vieilles à la base, gardez toujours une ou deux charpentières de bonne taille et supprimez les autres. Tailler les branches de l’année, à 3 ou 4 boutons. Pour obtenir une floraison importante, courber et attacher régulièrement les branches à 20 ou 30°. Chaque courbure entraîne une pousse latérale qui se termine par un bouquet de fleurs.', NULL, 'croissance rapide', ''),
(51, 'aromatique', 'Stevia rebaudiana', 'img\\imgBDD\\SteviaRebaudiana.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'elle doit être cultivée en pot pour pouvoir être rentrée l\'hiver. Elle craint le froid intense et surtout l\'excès d\'humidité et le manque d\'aération. La conserver entre 10 et 15°C dans un endroit sec et lumineux avec quelques arrosages assez espacés. Ne laissez pas fleurir votre stevia, car elle meurt juste après. Il est conseillé de ne pas tailler la Stevia pendant l\'hiver.  ', 'elle doit être cultivée en pot pour pouvoir être rentrée l\'hiver. Elle craint le froid intense et surtout l\'excès d\'humidité et le manque d\'aération. La conserver entre 10 et 15°C dans un endroit sec et lumineux avec quelques arrosages assez espacés. Ne laissez pas fleurir votre stevia, car elle meurt juste après. Il est conseillé de ne pas tailler la Stevia pendant l\'hiver.', NULL, NULL, ''),
(52, 'aromatique', 'LEVISTICUM officinale (Ache des montagnes, Livèche)', 'img\\imgBDD\\LEVISTICUM.png', 'jaune', 'vert', 1, NULL, 'juillet-août', NULL, 'caduc', 'soleil', 'profonde, fertile, fraîche et drainée', 'touffe dressée', '3 au m²', NULL, 'ce céleri vivace sert à la confection de bouillons, sauces et soupes. Les graines qui sont aussi très parfumées, servent à parfumer les pâtisseries.', 'ajouter un épais paillage et arroser fréquemment en été. Couper les hampes florales mais en laisser quelques-unes pour utiliser les graines.', NULL, 'Le cèleri vivace a aussi des vertues médicinales appéritives diurétiques, hypoglycémiantes, aphrodisiaques, digestives et carminatives. On utilise toute la plante en décoction, jus, vin de cèleri et alcoolature en usage interne. En usage externe on peut en faire des bains et même des fumigations.', ''),
(53, 'aromatique', 'ORIGANUM vulgare (Origan) ', 'img\\imgBDD\\Origan.png', 'rose', 'vert', 1, NULL, 'juillet-septembre', NULL, 'persistant', 'soleil', 'sec et frais, drainé', 'touffe buissonnante', '6 au m²', NULL, 'plante aromatique majeure de la cuisine méditerranéenne. Frais ou séché, surtout avec les plats à base de tomates cuites, on peut aussi en faire des infusions et un vin d\'origan. Les fleurs fraiches parfument les plats. Cette plante médicinale est un puissant antiseptique. On l\'utilise comme le thym, comme plante digestive, antispasmodique,  en infusion ou en huile essentielle. On la reconnait riche en antioxydant. en vitamine K et E, en fer, calcium et manganèse.', 'Couper les fleurs fanées pour prolonger les floraisons. Tailler les tiges sèches durant l\'hiver', NULL, NULL, ''),
(54, 'aromatique', 'FOENICULUM vulgare \'purpureum\' (fenouil bronze)', 'img\\imgBDD\\FenouilBronze.png', 'jaune', 'pourpre ', 2, NULL, 'juillet-août', NULL, 'caduc', 'soleil', 'sec', 'touffe dressée', '3 au m²', NULL, 'fond de massif', 'Tailler les parties sèches dès qu\'elles ne sont plus décoratives ou avant la dissémination des graines pour éviter les auto-semis envahissants. Eliminer rapidement les jeunes plants issus des semis spontanés, avant que leur racine pivotante ne soit trop développée.', NULL, 'odorante et comestible', ''),
(55, 'aromatique', 'FOENICULUM vulgare (fenouil)', 'img\\imgBDD\\Fenouil.png', 'jaune', 'vert', 2, NULL, 'juillet-septembre', NULL, 'caduc', 'soleil', 'sec', 'touffe dressée', '3 au m²', NULL, 'plante graphique apportant du volume dans les massifs.', 'ailler les parties sèches dès qu\'elles ne sont plus décoratives ou avant la dissémination des graines pour éviter les auto-semis envahissants. Eliminer rapidement les jeunes plants issus des semis spontanés, avant que leur racine pivotante ne soit trop développée.', NULL, 'comestible, feuillage et graines', ''),
(56, 'aromatique', 'ARTEMISIA abrotanum (Armoise citron, aurone)', 'img\\imgBDD\\ArmoiseCitron.png', 'jaune', 'vert grisâtre', 1, NULL, 'juillet-août', NULL, 'semi-persistant', 'soleil', 'sec, drainé, supporte le calcaire', 'touffe dressée', '3 au m²', NULL, 'sert à confectionner des liqueurs, se marie avec les salades, les poissons, les viandes grasses ou pour aromatiser le vinaigre. Médicinale : vermifuge, diurétiques, tonique, cicatrisante, astringent, stomachique...', 'Épointer après la floraison pour enlever les fleurs fanées et arrondir et ramifier la touffe. Rabattre le feuillage à 15 cm en fin d\'hiver.', NULL, NULL, ''),
(57, 'aromatique', 'CALAMINTHA grandiflora (Thé de l\'Aubrac)', 'img\\imgBDD\\TheAubrac.png', 'rose', 'vert', 0, NULL, 'juin-août', NULL, 'caduc', 'soleil, mi-ombre', 'riche, fertile, bien drainé supporte le calcaire', 'touffe buissonnante', '6 au m²', NULL, 'feuilles et fleurs sont comestibles ; excellentes tisanes, desserts, salades de fruits, boissons...', 'Supprimer les inflorescences fanées pour prolonger les floraisons et pincer les tiges pour favoriser une nouvelle végétation.', NULL, 'attire abeilles et papillons', ''),
(58, 'aromatique', 'Origan grec (Origanum vulgare subsp. hirtum)', 'img\\imgBDD\\OriganGrec.png', 'blanche', 'vert', 0, 0, 'été', NULL, 'persistant', 'soleil, mi-ombre', 'drainé, supporte le calcaire', NULL, NULL, NULL, 'en cuisine, ajouter en fin de cuisson. En tisane favorise digestion, traditionnellement utilisé contre rhumes, angines, toux.', 'tailler régulièrement pour conserver un port compact. Tailler en fin de floraison.', NULL, 'un des origans les plus parfumés, saveur puissante et épicée', ''),
(59, 'aromatique', 'Origan commum \'Thumbles variety\' (Origanum vulgare)', 'img\\imgBDD\\OriganCommum.png', 'rose', 'doré', 0, 1, 'mai-octobre', NULL, 'caduc', 'soleil', 'sec', NULL, NULL, NULL, 'feuilles séchées en cuisine, sommités fleuries et graines en phytothérapie.', 'tailler régulièrement pour conserver un port compact. Tailler en fin de floraison.', NULL, 'mellifère, nectarifère', ''),
(60, 'aromatique', 'Sauge cassis, sauge andine (Salvia discolor)', 'img\\imgBDD\\SalviaDiscolor.png', 'bleu indigo presque noir', 'argenté', 1, 1, 'juin-sept', NULL, 'persistant', 'soleil, mi-ombre', 'léger, fertile, drainé, frais', NULL, NULL, NULL, 'les feuilles s’utilisent finement découpées dans des salades ou des salades de fruits ou en décoction pour l\'utiliser en jus ou fond de sauce.', 'la culture en extérieur est possible dans les régions plus clémentes, autrement cultivez-la en pot', 'sa rusticité n’excède pas – 3 °C en situation protégée et en sol sec l’hiver.', NULL, ''),
(61, 'aromatique', 'Valériane (VALERIANA officinalis)', 'img\\imgBDD\\Valeriane.png', 'blanche', 'vert', 1, 1, 'juin-juillet', NULL, 'caduc', 'soleil, mi-ombre', 'lourd, frais', 'touffe buissonnante ', NULL, NULL, 'décorative et médicinale traditionnellement utilisée comme sédatif et antispasmodique (racines)', 'binages fréquents, paillage', NULL, NULL, ''),
(62, 'aromatique', 'Salvia officinalis \'Icterina\' (Sauge officinale)', 'img\\imgBDD\\Icterina.png', 'violet', 'panaché doré', 1, 1, 'mai-juin', NULL, 'persistant', 'soleil', 'sec, bien drainé', 'touffe buissonnante', NULL, NULL, NULL, 'couper les inflorescences fanées. Taillez en fin d\'hiver pour conserver une touffe compacte.', NULL, NULL, ''),
(63, 'aromatique', 'Ciboule de Chine (Allium tuberosum odorum chinensis)', 'img\\imgBDD\\CibouleChine.png', 'blanc', 'vert', 1, NULL, 'août-septembre', NULL, 'caduc', 'soleil, mi-ombre', 'tous, drainé, supporte sec', NULL, NULL, NULL, 'goût proche de l’ail, mais plus doux. Feuilles et fleurs sont condimentaires et comestibles : salades, omelettes...', 'biner, pailler, tailler régulièrement pour avoir du feuillage', NULL, 'se congèle bien', ''),
(64, 'aromatique', 'Ciboulail, ciboulette de Chine (Allium tuberosum)', 'img\\imgBDD\\CibouletteChine.png', 'blanche', 'vert', 1, 0, NULL, NULL, 'caduc', 'soleil', 'frais, humifère, drainé', NULL, NULL, NULL, 's’utilise dans de nombreux plats : salades, potages...', 'n’arroser que quand le sol est sec, rabattre les tiges régulièrement', NULL, 'se congèle très bien', ''),
(65, 'aromatique', 'Laurier-sauce (Laurus nobilis)', 'img\\imgBDD\\LaurierSauce.png', NULL, 'vert', 7, NULL, NULL, NULL, 'persistant', 'soleil, mi-ombre', 'léger, drainé, humifère', NULL, NULL, NULL, 's’utilise en isolé, en haie. Indispensable pour le bouquet garni..', 'aucun sauf s’il est cultivé en pot', 'de croissance rapide il peut devenir envahissant avec de nombreux rejets', NULL, ''),
(66, 'aromatique', 'MERTENSIA maritima (Plante à goût d\'huître)', 'img\\imgBDD\\MERTENSIA.png', 'bleu', 'gris bleuté', 0, 0, 'été', NULL, 'caduc', 'soleil, mi-ombre', 'frais, drainé', 'touffe étalée', NULL, NULL, 'légume-feuille perpétuel, on l´utilise le plus souvent crue pour qu\'elle révèle toute sa saveur, dans des plats à base de poissons, en salade, en pesto ou conservée dans du vinaigre tout comme la salicorne. Récolte : les feuilles sont fragiles et s\'oxydent rapidement, il conviendra donc de récolter au fur et à mesure des besoins.', NULL, NULL, NULL, ''),
(67, 'aromatique', 'RHEUM rhabarbarum (Rhubarbe)', 'img\\imgBDD\\Rhubarbe.png', NULL, 'vert', 1, 1, NULL, NULL, 'caduc', 'mi-ombre', 'frais – humide, drainé, humifère', 'touffe buissonnante', NULL, NULL, 'on consomme les pétioles, usage médical, accumulatrice minéraux. Récolte : avant fin juin (acide oxalique)', 'bien pailler, bon apport de compost', NULL, NULL, ''),
(68, 'aromatique', 'ROSMARINUS officinalis  \'Majorca Pink\' (Romarin)', 'img\\imgBDD\\Romarin.png', 'rose', 'vert', 1, 1, 'automne et printemps', NULL, 'persistant', 'soleil', 'drainé, pauvre, sec, supporte calcaire', 'touffe buissonnante', NULL, NULL, 'massif d’arbustes, bac,  au potager, cuisine, médicinale', 'tailler après floraison', NULL, 'mellifère', ''),
(69, 'aromatique', 'HELICHRYSUM italicum subsp. Italicum (Hélichryse de Corse)', 'img\\imgBDD\\HelichryseCorse.png', 'jaune', 'vert-gris', 0, 0, 'juin-août', NULL, 'persistant', 'soleil', 'drainé, pauvre, sec, supporte calcaire', 'touffe', NULL, NULL, 'massif de vivaces, médicinale (anti-hématome)', 'tailler après floraison', NULL, 'mellifère', ''),
(70, 'aromatique', 'AGASTACHE nepetoides (Agastache géante)', 'img\\imgBDD\\AgastacheGeante.png', 'blanc-jaune', 'vert', 2, 1, 'sept-nov', NULL, 'caduc', 'soleil, mi-ombre', 'tous', 'touffe érigée', '3 au m²', NULL, 'médicinale', 'tailler au plus tard au démarrage de la végétation au printemps', NULL, NULL, ''),
(71, 'aromatique', 'THYMUS vulgaris \'Varico 3\' (Thym)', 'img\\imgBDD\\Thym.png', 'rose', 'vert', 0, NULL, 'mai-sept', NULL, 'persistant', 'soleil', 'sec, calcaire, sableux, caillouteux.', NULL, NULL, NULL, 'médicinale. Variété développée pour sa teneur plus élevée en huiles essentielles et sa richesse en thymol. Ce dernier a des propriétés antibactériennes et antioxydantes.', 'tailler court lors de la récolte, pendant la floraison.', NULL, NULL, ''),
(72, 'aromatique', 'THYMUS vulgaris \'Compactus\' (Thym compact)', 'img\\imgBDD\\ThymCompact.png', 'rose pâle', 'vert', 0, 0, 'mai-sept', NULL, 'persistant', 'soleil', 'sec, drainé, calcaire', NULL, NULL, NULL, 'culinaire (grillades, légumes) et médicinales', 'tailler court lors de la récolte, pendant la floraison.', NULL, NULL, ''),
(73, 'aromatique', 'PETROSELINUM sativum (Persil plat, commun)', 'img\\imgBDD\\PersilPlat.png', NULL, 'vert', 0, 0, NULL, NULL, 'semi-persistant', 'soleil', 'frais, riche, bien drainé', NULL, NULL, NULL, 'partout en cuisine, médicinale', 'tailler régulièrement pour favoriser de nouvelles repousses, et ne pas hésiter à le rabattre quand son développement devient trop important.', NULL, NULL, ''),
(74, 'aromatique', 'CORIANDRUM sativum (Coriandre)', 'img\\imgBDD\\Coriandre.png', NULL, 'vert', 1, 0, NULL, NULL, 'semi-persistant', 'soleil', 'frais, riche, bien drainé', NULL, NULL, NULL, 'les feuilles et les graines', 'arroser régulièrement et tailler la partie supérieure de la plante pour stimuler la production de nouvelles feuilles et éviter qu ‘elle monte en graines prématurément.', NULL, NULL, ''),
(75, 'aromatique', 'ARTEMISIA dracunculus (Estragon français)', 'img\\imgBDD\\EstragonFrancais.png', NULL, 'vert', 1, NULL, 'Juin - Juillet', NULL, 'caduc', 'soleil', 'frais, riche et drainant.', 'Touffe dressée', '5 au m²', NULL, 'on l\'utilise en cuisine dans les salades, les sauces. Il sert aussi à parfumer le vinaigre, les cornichons et certaines liqueurs. C\'est aussi une plante médicinale à utiliser en infusion ou en liqueur.', 'La touffe étant souvent désordonnée, la taille régulière pour l\'utilisation en cuisine favorisera la ramification. Protéger en régions très froides.', NULL, NULL, ''),
(76, 'aromatique', 'Cymbopogon citratus', 'img\\imgBDD\\citronnelle.png', NULL, 'vert', 1, NULL, NULL, NULL, 'vivace si maintenue au delà de 7°C', 'soleil', NULL, NULL, NULL, NULL, 'utilisée en cuisine, comme plante médicinale, mais également pour éloigner les moustiques et les mouches.', 'la rentrer l\'hiver hors gel. Pendant la saison chaude arroser fréquemment. Réduire l\'arrosage pendant le repos végétatif et arrêter la taille.', NULL, NULL, ''),
(77, 'aromatique', 'Pelargonium asperum (Géranium rosat)', 'img\\imgBDD\\GeraniumRosat.png', 'rose', 'vert', 1, NULL, 'été', NULL, 'persistant à semi-persistant', 'soleil', 'soleil', NULL, NULL, NULL, 'utilisé pour éloigner les moustiques, mais aussi comme plante médiciale et en cuisine', 'rentrer les pots l’hiver dans une pièce pas ou peu chauffée et lumineuse. Les arrosages devront être réguliers au printemps et en été, mais très limités en hiver.', NULL, NULL, ''),
(78, 'aromatique', 'THYMUS citriodorus', 'img\\imgBDD\\ThymCitron.png', 'Rose', 'vert', 0, NULL, 'Juin - Août', NULL, 'persistant', 'soleil', 'sec et drainé', 'Touffe buissonnante', '9 au m²', NULL, 'parfum citronné très marqué. Il s\'utilise dans de nombreux plats et en tisane ou boisson rafraichissante.', 'Couper les tiges florales fanées dès qu\'elles ne sont plus décoratives en épointant, si besoin, les rameaux. Tailler en petite touffe, en fin d\'hiver pour éviter qu\'elle ne se dégarnisse.', NULL, NULL, ''),
(79, 'aromatique', 'THYMUS vulgaris', 'img\\imgBDD\\ThymCommun.png', 'Rose', 'vert', 1, NULL, 'avril-mai', NULL, 'persistant', 'soleil', 'sec et drainé', 'Touffe buissonnante', '9 au m²', NULL, 'c\'est la base du bouquet garni.', 'couper les tiges florales fanées dès qu\'elles ne sont plus décoratives en épointant, si besoin, les rameaux. Tailler en petite touffe, en fin d\'hiver pour éviter qu\'elle ne se dégarnisse.', NULL, NULL, ''),
(80, 'aromatique', 'SATUREJA montana', 'img\\imgBDD\\SarrietteMontagnes.png', 'Blanc', 'vert', 0, NULL, 'Juin - Août', NULL, 'persistant', 'soleil', 'sec', 'Touffe buissonnante', '6 au m²', NULL, 'bac, rocaille, jardin sur gravier, couvre-sol allélopathique, jardin aromatique.', 'Couper les inflorescences fanées dès qu\'elles ne sont plus décoratives en raccourcissant la touffe. Tailler assez court en fin d\'hiver.', NULL, NULL, ''),
(81, 'aromatique', 'ROSMARINUS officinalis (Romarin)', 'img\\imgBDD\\RomarinOfficinalis.png', 'Bleu', 'vert', 2, NULL, 'Mai - Juin', NULL, 'persistant', 'soleil', 'sec et frais.', 'Touffe dressée', '1 au m²', NULL, 'bac, massif d\'arbustes, plante semencière pour revégétalisation de talus et espaces dégradés, jardin aromatique, jardin en bord de mer.', 'Tailler après floraison.', NULL, 's\'utilise en cuisine et comme plante médicinale.', ''),
(82, 'aromatique', 'THYMUS hirsutus', 'img\\imgBDD\\ThymHirsute.png', 'Rose', 'vert', 0, NULL, 'juin-juillet', NULL, 'persistant', 'soleil', 'sec et drainé', 'Touffe buissonnante', '9 au m²', NULL, 'c\'est la base du bouquet garni. Il aromatise de nombreux plats et peut se consommer en tisane ou en boisson rafraichissante mélangée à la menthe ou à la verveine citronnelle.', 'couper les tiges florales fanées dès qu\'elles ne sont plus décoratives en épointant, si besoin, les rameaux. Tailler en petite touffe, en fin d\'hiver pour éviter qu\'elle ne se dégarnisse.', NULL, 'c\'est un formidable couvre-sol qui résiste partiellement au piétinement.', ''),
(83, 'aromatique', 'ROSMARINUS officinalis prostrata (ROMARIN rampant)', 'img\\imgBDD\\RomarinRampant.png', 'Bleu', 'vert', 1, NULL, 'Mai - Juin', NULL, 'persistant', 'soleil', 'sec et frais.', 'Touffe dressée', '1 au m²', NULL, 'bac, muret, talus, grand massif couvre-sol, jardin allélopathique.', 'Tailler après floraison.', NULL, 'peut s\'utiliser comme couvre-sol.', ''),
(84, 'aromatique', 'HYSSOPUS officinalis (Hysope)', 'img\\imgBDD\\Hysope.png', 'bleu foncé', 'vert', 1, NULL, 'juin-septembre', NULL, 'semi-persistant', 'soleil', 'sec, léger, drainé', 'touffe buissonnante', '6 au m²', NULL, 'rocaille, jardin sur gravier, jardin aromatique.', 'Pincer après la floraison les fleurs fanées et le feuillage pour conserver la touffe bien compacte. Tailler en petite touffe courte avant le démarrage de la végétation au printemps.', NULL, 'médicinale très attractive pour papillons', ''),
(85, 'aromatique', 'Persicaria odorata (coriandre vietnamienne, rau-ram)', 'img\\imgBDD\\CoriandreVietnamienne.png', 'rose pâle', 'vert', 0, NULL, NULL, NULL, 'semi-persistant', 'mi-ombre, soleil', 'riche, drainé et frais', 'couvre-sol', NULL, NULL, 'très présente dans la cuisine asiatique, elle apporte une note poivrée et citronnée proche de la coriandre.', 'tailler court et régulièrement, les jeunes feuilles sont plus aromatiques que les plus anciennes. Rentrer l\'hiver si les températures sont inférieures à -9°C.', NULL, NULL, ''),
(86, 'aromatique', 'ALOYSIA triphylla (Verveine citronelle)', 'img\\imgBDD\\VerveineCitronelle.png', 'blanc', 'vert', 1, NULL, 'juillet-août', NULL, 'caduc', 'soleil', 'frais, riche  et drainé', 'touffe buissonnante', '3 au m²', NULL, 'pour des boissons ou parfumer plats salés et desserts ', 'rabattre la touffe à 15 cm en fin de saison et pailler pour protéger les racines du gel. Retirer le paillage en mars, dès que la période de froid est passée, le paillage pouvant faire pourrir les jeunes pousses issues des bourgeons sur les racines.', NULL, 'elle repousse les pucerons et les moustiques. A placer dans un endroit stratégique au jardin', ''),
(87, 'aromatique', 'Agastache rugosa (Agastache, menthe coréenne)', 'img\\imgBDD\\AgastacheRugosa.png', 'bleu', 'vert', 1, NULL, 'juillet-octobre', NULL, 'caduc', 'soleil mi-ombre', 'sec, riche, drainé', 'touffe dréssée', '4 au m²', NULL, 'Massif de vivaces. ', 'Supprimer les inflorescences fanées pour prolonger les floraisons. Rabattre en fin d\'automne dès que la touffe sèche n\'est plus décorative et protéger en régions très froides.', NULL, 'La menthe coréenne est couramment utilisée dans la pharmacopée chinoise, où elle est considérée comme l\'une des 50 herbes fondamentales mais aussi pour parfumer des plats de légumes frais ou cuits, les viandes, les poissons et les salades de fruits. Fleurs comestibles.', ''),
(88, 'aromatique', 'ALLIUM schoenoprasum (Ciboulette)', 'img\\imgBDD\\Ciboulette.png', 'rose', 'vert', 0, NULL, 'mai-juin', NULL, 'caduc', 'soleil, mi-ombre', 'sec et frais', 'touffe hérissée', '6 au m²', NULL, 'excellente en cuisine', 'pour prolonger la végétation et l\'utilisation en cuisine, couper les fleurs fanées et rabattre une partie du feuillage pour obtenir des tiges toujours fines.', NULL, NULL, ''),
(89, 'aromatique', 'GYNOSTEMMA Pentaphyllum (Jiaogulan, herbe de l\'immortalité)', 'img\\imgBDD\\Jiaogulan.png', 'jaune', 'vert', 2, 1, 'été', NULL, 'semi-persistant', 'ombre, mi-ombre', 'riche et frais', 'grimpante', 'planter tous les 50 cm', NULL, 'couvre-sol ou palissage. Médicinale : tisanes', 'bien pailler pour éviter les adventices et garder de l’humidité', NULL, NULL, ''),
(90, 'aromatique', 'ARTEMISIA ANNUA (Armoise annuelle)', 'img\\imgBDD\\ARMOISEAnnuelle.png', 'jaune', 'vert', 2, 1, NULL, NULL, 'semi-persistant', 'soleil, mi-ombre', 'léger, drainé', 'touffe buissonnante', NULL, NULL, 'Médicinale : tisanes. Récolter au plus tard lors de l’apparition des boutons floraux', 'bien pailler pour éviter les adventices et garder de l’humidité.\r\nhttps://blog.kokopelli-semences.fr/presentation-de-lartemisia/', NULL, NULL, ''),
(91, 'aromatique', 'PERILLA frutescens (shiso, basilic japonais)', 'img\\imgBDD\\basilicjaponais.png', NULL, 'vert ou/et pourpre', 1, 1, NULL, NULL, 'caduc', 'soleil', 'riche, drainé', 'touffe buissonnante', NULL, NULL, 's’utilise partout en cuisine. Propriétés digestives, antiseptiques et antiallergiques.', 'pincer la tige principale pour ramifier ', NULL, 'mellifère', ''),
(92, 'aromatique', 'CELERI vert à couper (Apium graveolens)', 'img\\imgBDD\\Apiumgraveolens.png', NULL, 'vert', 1, NULL, NULL, NULL, 'persistant', 'soleil', 'riche, frais', 'touffe dressée', NULL, NULL, 's’utilise comme condiment dans les potages, pots au feu ; ses côtes cuites ou crues. Propriétés antirhumatismales, digestives, reminéralisantes...', 'on les récolte par pied entier en coupant au ras du sol. Prévoir un bon paillage pour maintenir l’humidité', NULL, NULL, ''),
(93, 'aromatique', 'THYMUS FRAGANTISSIMUM (Thym orange)', 'img\\imgBDD\\Thymorange.png', 'blanc rosé', 'vert', 0, 0, 'juin-sept', NULL, 'persistant', 'soleil', 'léger, bien drainé, sec, de préférence calcaire', 'coussin', NULL, NULL, 'cuisine et médicinale', 'maintenir le sol propre avec des binages ou un paillage végétal. On effectue une taille sévère en mars, puis on rabat les tiges florales fanées après la floraison.', NULL, NULL, ''),
(94, 'aromatique', 'VERVEINE d\'Argentine (Aloysia polystacha)', 'img\\imgBDD\\Aloysiapolystacha.png', 'blanche', 'vert', 2, 1, NULL, NULL, 'caduc', 'soleil', 'riche, drainé', 'touffe buissonnante', NULL, NULL, 'avec ses notes d’agrume et de menthe elle s’utilise en tisane, liqueur ou dans les desserts. Propriétés digestives et sédatives.', 'résiste jusqu’à -7°C. En climat doux, avant l’hiver, réaliser une taille sévère et mettre en place un épais paillage.', NULL, NULL, ''),
(95, 'aromatique', 'SALVIA Apiana (Sauge blanche)', 'img\\imgBDD\\Saugeblanche.png', 'blanc rosé', 'gris, presque blanc', 1, 1, 'printemps', NULL, 'persistant', 'soleil', 'sec, pauvre, drainé', NULL, NULL, NULL, 'massif de vivaces, jardin sur gravier, conteneur, cuisine, usage médicinal : antibactérien', 'supprimer les fleurs fanées pour prolonger les floraisons. L\'hiver, l’abriter sous un épais paillage.', NULL, 'La sauge blanche incarne une plante sacrée pour les peuples amérindiens. Lors des cérémonies religieuses, les feuilles, le plus souvent réunies en fagots et brûlées comme de l\'encens, sont traditionnellement utilisées de manière rituelle en guise de purification des lieux et des personnes lors de cérémonies chamaniques.', ''),
(96, 'aromatique', 'Sucre des Aztèques, verveine sucrante (Lippia dulcis)', 'img\\imgBDD\\Lippiadulcis.png', 'blanche', 'vert', 0, NULL, NULL, NULL, 'persistant', 'soleil, ombre légère (sud France)', 'humifère, léger, frais', NULL, NULL, NULL, 'édulcorant naturel, plante aromatique et médicinale à utiliser fraîche ou séchée', 'tailler à la sortie de l’hiver et apporter du compost mûr', 'peu rustique (-6 à 10°C). La protéger d’un voile d’hivernage ou la renter hors gel.', NULL, ''),
(97, 'aromatique', 'Marjolaine (Origanum majorana)', 'img\\imgBDD\\Origanummajorana.png', 'blanche', 'vert', 0, NULL, 'été', NULL, 'persistant', 'soleil', 'drainé, sec', NULL, NULL, NULL, 'feuilles fraîches ou séchées, seules ou avec thym, romarin, sauge off…  pour de nombreuses préparations. Traditionnellement utilisée comme antiseptique ou pour traiter anxiété, insomnie, migraine ou affections bronches.', 'Fin juin et mi-septembre, rabattez la touffe afin de lui redonner un peu de vigueur et l\'aider à former de belles feuilles.', NULL, 'les fleurs aussi sont comestibles.', ''),
(98, 'aromatique', 'Estragon du Mexique (TAGETES lucida)', 'img\\imgBDD\\TAGETESlucida.png', 'jaune-orangé', 'vert', 1, 1, 'été', NULL, 'semi-persistant', 'soleil, mi-ombre', 'fertile, drainé, sec', NULL, NULL, NULL, 'accompagne les volailles, salades, poissons, omelettes ou desserts. S’utilise traditionnellement en infusion pour soigner maux d’estomac.', 'l\'hiver, l’abriter sous un épais paillage de feuilles mortes. En dessous de -5 C il faut rentrer les plants.', NULL, 'les fleurs aussi sont comestibles.', ''),
(99, 'aromatique', 'Mélisse, citronnelle (MELISSA officinalis)', 'img\\imgBDD\\MELISSA.png', 'blanche', 'vert', 1, 1, 'été', NULL, 'caduc', 'soleil, mi-ombre', 'frais, profond, riche', NULL, NULL, NULL, 'les feuilles et les fleurs sont utilisées fraîches ou séchées en cuisine et en tisane, traditionnellement pour favoriser le sommeil, la digestion...', 'rabattre régulièrement les tiges pour favoriser la croissance de nouvelles pousses', NULL, NULL, ''),
(100, 'aromatique', 'SATUREJA douglasii (Menthe indienne)', 'img\\imgBDD\\Mentheindienne.png', 'blanche', 'vert', 0, 1, 'juin-juillet', NULL, 'persistant', 'soleil', 'bien drainé, humifère', NULL, NULL, NULL, 'suspension, massif, pot, potager, couvre sol. S’utilise crue en salade, en tisane', NULL, 'gélive', NULL, ''),
(101, 'aromatique', 'RUTA graveolens (Rue des jardins)', 'img\\imgBDD\\Ruedesjardins.png', 'jaune', 'vert bleuté', 1, 1, 'juin-août', NULL, 'vivace', 'soleil', 'tous, drainé, sec', NULL, NULL, NULL, 'massif de vivaces, jardin potager, médicinale. Attention, la rue peut provoquer des réactions cutanées', 'rabattre les branches à 15 cm du sol au printemps', NULL, 'propriétés répulsives envers pucerons et chats', ''),
(104, 'aromatique', 'CHAMAEMELUM nobile (Camomille romaine)', 'img\\imgBDD\\Camomilleromaine.png', 'blanche cœur jaune', 'vert', 0, 0, 'été', NULL, 'persistant', 'soleil', 'riche et drainé', NULL, NULL, NULL, 'couvre-sol, médicinale', 'cueillir les fleurs en été, juste avant leur épanouissement complet. Tailler dès la fin de floraison', NULL, NULL, ''),
(105, 'aromatique', 'OENOTHERA biennis (Onagre bisannuelle)', 'img\\imgBDD\\Onagrebisannuelle.png', ' jaune', 'vert clair', 0, 1, 'été', NULL, 'caduc', 'soleil à mi-ombre', 'sec, drainé', NULL, NULL, NULL, 'comestible, médicinale', NULL, NULL, 'toute la plante est utilisable : les racines au goût sucré se mangent crues ou cuites (avant fleurissement), les fleurs décorent les salades, les graines peuvent remplacer le pavot, les feuilles sont consommées cuites à l\'eau, comme un légume (changer l’eau 2 fois).\r\nL\'huile d\'onagre est obtenue à partir de ses graines, elle est bénéfique pour la peau. ', ''),
(106, 'aromatique', 'CENTELLA asiatica (Herbe du Tigre, Gotu Kola)', 'img\\imgBDD\\GotuKola.png', NULL, 'vert', 0, 1, NULL, NULL, 'caduc', 'mi-ombre', 'semi aquatique, sol sablonneux, argileux, humifère', NULL, NULL, NULL, 'couvre-sol. Utilisée en phytothérapie', 'elle est supposée être gélive, la renter l’hiver', NULL, NULL, ''),
(107, 'aromatique', 'GLYCYRRHIZA glabra (Réglisse)', 'img\\imgBDD\\Reglisse.png', 'violet', 'vert', 1, 1, 'juin-août ', NULL, 'caduc', 'soleil', 'tous, préfère sol riche, profond et drainé', NULL, NULL, '-16°C', 'potager, en cuisine, phytothérapie. Récolter à la fin de la troisième année, à l\'automne, à la chute des feuilles. ', 'rabattre les tiges sèches en fin d’hiver. Pailler et arroser au pied l’été', 'peut se monter invasive', 'fixateur d’azote , mellifère', ''),
(108, 'aromatique', 'VIOLA odorata blanche (violette odorante)', 'img\\imgBDD\\violetteodorante.png', 'blanche', 'vert', 0, NULL, 'mars à juin', NULL, 'caduc', 'mi-ombre, ombre', 'sec et frais, humifère', NULL, NULL, NULL, 'bordures de massifs, talus, couvre-sol. Phytothérapie : les fleurs et les feuilles de la violette odorante sont préconisées en cas d\'affections broncho-pulmonaires, comme les bronchites ou la toux, mais aussi contre les douleurs rhumatismales. En utilisation externe, la violette odorante permet de lutter contre la nervosité, le stress et les insomnies.', NULL, NULL, 'toute la plante se mange', ''),
(109, 'aromatique', 'IPHEION uniflorum (Ail des Incas)', 'img\\imgBDD\\AilIncas.png', 'bleu pâle', 'vert', 0, 0, 'mars-avril', NULL, 'caduc', 'soleil, mi-ombre', 'léger, bien drainé. Supporte les sols pauvres et secs l’été', NULL, NULL, '-15°C', 'parterre, pelouse, bordure, jardinière, rocaille. Fleurs et feuilles sont comestibles', 'le diviser tous les 5 ans', NULL, 'mellifère', ''),
(110, 'médicinale', 'SYMPHYTUM grandiflorum \'Hidcote Pink\' (Consoude)', 'img\\imgBDD\\Consoude.png', 'rose', 'vert', 0, 1, 'avril-mai', NULL, 'caduc', 'soleil, mi-ombre', 'profond et frais. Résiste à la sécheresse', 'tapissant, couvre-sol', NULL, NULL, 'excellentes accumulatrices de minéraux (K), utilisées de ce fait sous et autour des arbres et arbustes à fruits. Elles servent également de paillage. Médicinale, mellifère.', 'couper les inflorescences fanées dès qu\'elles ne sont plus décoratives en diminuant la végétation. Nettoyer la touffe en fin d\'hiver. Limiter les rhizomes s\'ils envahissent.', NULL, NULL, ''),
(111, 'médicinale', 'CHRYSANTHEMUM parthenium (Grande camomille)', 'img\\imgBDD\\Grandecamomille.png', 'blanc cœur jaune', 'vert', 1, 0, 'juillet-août', NULL, 'caduc', 'soleil, mi-ombre', 'pas trop sec à frais.', 'touffe buissonnante', NULL, NULL, 'massif de vivaces, médicinale (migraines), plante refuge pour les bombyles', 'la tailler bien court en fin d\'hiver, juste avant le redémarrage pour obtenir des touffes biens garnies', 'vivace de courte durée mais qui se ressème sur place', NULL, ''),
(112, 'médicinale', 'HYPERICUM perforatum (Millepertuis)', 'img\\imgBDD\\MillepertuisPerforatum.png', 'jaune', 'vert', 1, 0, NULL, NULL, 'caduc', 'soleil', 'tous, pauvre, drainé. Supporte le calcaire, supporte la sécheresse estivale', NULL, NULL, '-15°C', 'massif, bordure, talus, potager, phytothérapie. ', 'rabattre les tiges sèches en fin d’hiver. ', NULL, 'mellifère', ''),
(113, 'médicinale', 'Bulbine frutescens (Bulbine)', 'img\\imgBDD\\Bulbine.png', 'jaune', 'vert', 1, NULL, 'mai-novembre', NULL, 'persistant', 'soleil', 'parfaitement drainé, non calcaire, sec', NULL, '2 au m²', 'jusqu\'à -5°C (avec des pics à -10°C pas trop longtemps)', 'La bulbine s\'utilise comme l\'Aloe vera ; en utilisation externe pour les rhumatismes, l\'eczéma, les plaies, les coups de soleil, les infections cutanées, l\'herpès, les piqûres d\'insectes, l\'acné, les ulcères buccaux et la peau fragile.', 'dans le bassin méditerranéen et la côte atlantique vous pouvez cultiver la bulbine directement en pleine terre au pied d\'un mur bien exposé. \r\nAilleurs, culture en pot dans un endroit ensoleillé et sec et la maintenir l\'hiver dans une véranda ou une pièce lumineuse hors gel. Pendant l\'hiver l\'arrosage doit être réduit au minimum. \r\nLes besoins en amendement sont très limités. ', NULL, NULL, ''),
(114, 'aromatique', 'MENTHE verte', 'img\\imgBDD\\MENTHEverte.png', 'mauve', 'vert', 1, NULL, 'juillet-sept', NULL, 'caduc', 'soleil, mi-ombre', 'riche et frais ', 'touffe étalée', '3 au m²', NULL, 'idéale pour les mojitos, comme pour de nombreux plats', 'tailler court régulièrement pour favoriser la croissance de jeunes pousses', 'plante invasive', NULL, ''),
(115, 'aromatique', 'MENTHE chocolat', 'img\\imgBDD\\MENTHEchocolat.png', 'mauve', 'vert', 1, NULL, 'juillet-sept', NULL, 'caduc', 'soleil, mi-ombre', 'riche et frais ', 'touffe étalée', '3 au m²', NULL, 'idéale pour la patisserie', 'tailler court régulièrement pour favoriser la croissance de jeunes pousses', 'plante invasive', NULL, ''),
(116, 'aromatique', 'MENTHE marocaine', 'img\\imgBDD\\MENTHEmarocaine.png', 'mauve', 'vert', 1, NULL, 'juillet-sept', NULL, 'caduc', 'soleil, mi-ombre', 'riche et frais ', 'touffe étalée', '3 au m²', NULL, 'idéale pour le thé à la menthe, comme pour de nombreux plats. Médicinale.', 'tailler court régulièrement pour favoriser la croissance de jeunes pousses', 'plante invasive', NULL, ''),
(117, 'aromatique', 'MENTHE bergamote', 'img\\imgBDD\\MENTHEbergamote.png', 'mauve', 'vert', 0, NULL, 'juin à septembre', NULL, 'caduc', 'soleil, mi-ombre', 'tous', 'touffe étalée', '3 au m²', NULL, 'en cuisine, principalement pour  des sauces, desserts et boissons. C\'est aussi une plante médicinale de premier plan.', 'rabattre la touffe plusieurs fois dans la saison de végétation et dès qu\'elle envahit pour renouveler le feuillage. Envahissante, lui réserver une place un peu à l\'écart du potager. Sinon la barricader derrière des bordures ou la cultiver en pot.', NULL, NULL, ''),
(118, 'aromatique', 'MENTHA x piperita (menthe poivrée)', 'img\\imgBDD\\menthepoivree.png', NULL, 'vert', 1, NULL, 'juillet-sept', NULL, 'caduc', 'soleil, mi-ombre', 'riche et frais', 'touffe étalée', '3 au m²', NULL, 'boissons et desserts. Médicinale : tonique, apéritive, facilite la digestion, soigne les problèmes de bronches, calme les nerfs, les crampes, les migraines et les insomnies..', 'tailler court régulièrement pour favoriser la croissance de nouvelles pousses', 'plante invasive ', NULL, ''),
(119, 'aromatique', 'MENTHA spicata \'Hollywood\'', 'img\\imgBDD\\MentheHollywood.png', NULL, 'vert', 1, NULL, 'juillet-sept', NULL, 'caduc', 'mi-ombre', 'riche et frais ', 'touffe étalée', '3 au m²', NULL, 'boissons, desserts... Déclinaison plus sucrée, chlorophyllée et fraîche que la menthe verte.', 'tailler court régulièrement pour favoriser la croissance de nouvelles pousses', 'plante invasive ', NULL, ''),
(122, 'aromatique', 'SALVIA chamaedryoides (Sauge)', 'img\\imgBDD\\SALVIAchamaedryoides.png', 'Bleu', 'Gris-argent', 1, NULL, 'mai à juillet remontant sept à nov', NULL, 'persistant', 'soleil', 'léger, bien drainé', 'Touffe buissonnante', '3 au m²', '-10 à -12°C', 'massif de vivaces et d\'arbustes, jardin sur gravier, jardin aromatique', 'Couper les inflorescences fanées pour prolonger les floraisons en pinçant le feuillage. Tailler en fin d\'hiver et éliminer les tiges en surnombre.', NULL, NULL, ''),
(123, 'aromatique', 'SALVIA multicaulis (Sauge)', 'img\\imgBDD\\SALVIAmulticaulis.png', 'violet clair puis pourpre', 'Gris-vert', 0, NULL, 'mars à mai', NULL, 'parfois partiellement caduc été et hiver', 'soleil', 'pauvre, parfaitement drainé', 'coussin tapissant', '6 au m²', NULL, 'rocaille, jardin sur gravier', NULL, NULL, NULL, ''),
(124, 'aromatique', 'SALVIA mellifera (Sauge)', 'img\\imgBDD\\SALVIAmellifera.png', 'blanc', 'vert sombre', 1, NULL, 'avril-mai', NULL, 'persistant, aromatique', 'soleil', 'léger, bien drainé', 'large boule', '1 au m²', '-6 à -8°C', NULL, NULL, NULL, NULL, ''),
(125, 'aromatique', 'SALVIA x jamensis \'Purple Queen\'', 'img\\imgBDD\\PurpleQueen.png', 'bleu-violet', 'vert sombre', 1, NULL, 'avril à juin puis sept à nov', NULL, 'persistant, aromatique', 'soleil', 'tous', 'touffe buissonnante', '2 au m²', NULL, NULL, NULL, NULL, NULL, ''),
(126, 'aromatique', 'SALVIA officinalis \'Purpurascens\'', 'img\\imgBDD\\SALVIAofficinalis.png', 'violet', 'pourpre', 1, NULL, 'mai-juin', NULL, 'persistant', 'soleil', 'sec, drainé', 'touffe buissonnante', '3 au m²', NULL, NULL, NULL, NULL, NULL, ''),
(127, 'aromatique', 'SALVIA microphylla (grahamii) (Sauge)', 'img\\imgBDD\\SALVIAmicrophylla.png', 'Rouge', 'vert', 1, NULL, 'Février - Novembre', 'Juillet - Novembre', NULL, 'soleil', 'caduc', 'Touffe buissonnante', '3 au m2', NULL, NULL, NULL, NULL, NULL, ''),
(128, 'aromatique', 'SALVIA fruticosa', 'img\\imgBDD\\SALVIAfruticosa.png', 'rose-violet', 'gris-vert', 1, NULL, 'mars-avril', NULL, 'persistant', 'soleil', 'pauvre, parfaitement drainé', 'touffe arrondie', '1 au m²', NULL, 'massif de vivaces et d\'arbustes, jardin sur gravier, jardin aromatique', NULL, NULL, NULL, ''),
(129, 'aromatique', 'Salvia Sclarea (sauge sclarée)', 'img\\imgBDD\\saugesclaree.png', 'Mauve', 'Gris-argent', 1, NULL, 'Avril - Novembre', 'Juin - Août', 'caduc', 'soleil', 'sol drainé', 'Touffe dressée', '3 au m²', NULL, NULL, NULL, NULL, 'médicinale', ''),
(130, 'aromatique', 'SALVIA officinalis (Sauge officinale)', 'img\\imgBDD\\Saugeofficinale.png', 'Bleu', 'Gris-argent', 1, NULL, 'Janvier - Décembre', 'Mai - Juin', 'persistant', 'soleil', 'sec et frais.', 'Touffe arrondie', '1-2 au m2', NULL, NULL, NULL, NULL, NULL, '');
INSERT INTO `plante` (`idPlante`, `TypePlante`, `NomPlante`, `imgPlante`, `CouleurFleur`, `CouleurFeuillage`, `Hauteur`, `Largeur`, `Floraison`, `Floraison_s_`, `TypeFeuillage`, `Exposition`, `TypeSol`, `Silhouette`, `Densite`, `Rusticite`, `Utilisation`, `Entretien`, `PetitMoins`, `PetitPlus`, `NomLatin`) VALUES
(131, 'aromatique', 'SALVIA pratensis (Sauge des prés)', 'img\\imgBDD\\Saugedespres.png', 'Bleu', 'vert', 1, NULL, 'Avril - Novembre', 'Juin - Octobre', 'caduc', 'soleil', 'sec', 'Touffe buissonnante', '4 au m2', NULL, NULL, NULL, NULL, NULL, ''),
(132, 'fruitier', 'PINUS pinea (Pin parasol, pin à pignons)', 'img\\imgBDD\\Pinparasol.png', NULL, 'vert', 20, 10, NULL, NULL, 'persistant', 'soleil', 'pauvre, drainé, pas trop sec à frais, acide ou neutre', NULL, NULL, '-7°C', 'Fruit : les pignons', NULL, NULL, NULL, ''),
(133, 'fruitier', 'ARAUCARIA araucana (Désespoir des singes)', 'img\\imgBDD\\Desespoirdessinges.png', NULL, 'vert', 15, 8, NULL, NULL, 'persistant', 'soleil', 'frais, bien drainé, humifère et d\'une bonne hygrométrie. Il n\'aime pas le calcaire', NULL, NULL, '-15°C', 'isolé, comestible, bois de qualité. Plante dioïque : il faut des sujets mâles et femelles pour avoir des graines. A ce stade de leur développement ces arbres ne sont pas différenciés. Fruits : cônes de 15 cm de long produisant des graines comestibles type pignons (200 à 300 !)', 'pailler l’été et prévoir un voile d\'hivernage les premières années', 'attention à son feuillage acéré, planter loin des habitations à cause du système racinaire puissant', NULL, ''),
(134, 'fruitier', 'SHEPHERDIA argentea\r\n(Baie de Buffalo)', 'img\\imgBDD\\BaieBuffalo.png', NULL, 'vert argenté', 4, 4, NULL, NULL, 'semi-persistant', 'soleil', 'tous, drainé supporte la sécheresse et le froid', NULL, NULL, '-20°C', 'massif, isolé, haie. Comestible. Plante dioïque : nécessitant des sujets mâles et femelles pour fructifier. A ce stade de développement la détermination n’est pas possible. Fruits : rouge, pulpe sucrée.', NULL, NULL, NULL, ''),
(135, 'fruitier', 'CORNUS mas (Cornouiller mâle, cornier)', 'img\\imgBDD\\cornier.png', 'jaune en février-mars', 'vert puis jaune', 5, 5, NULL, NULL, 'caduc', 'soleil', 'drainé, pauvre, supporte le calcaire', NULL, NULL, '-15°C', 'Plus productif avec une pollinisation croisée. massif, isolé, haie. Comestible, mellifère, médicinale, excellent bois. Fruits : rouges récoltés blets, goût agréable, crus ou cuits', 'apport de compost à l’automne', NULL, NULL, ''),
(136, 'fruitier', 'ELAEAGNUS multiflora \'Sweet Scarlet\' (Goumi du Japon)', 'img\\imgBDD\\GoumiJapon.png', NULL, 'vert argenté', 3, 2, NULL, NULL, 'semi-persistant', 'soleil, ombre légère', 'tous, drainé, pauvre, supporte la sécheresse', NULL, NULL, '-15°C', 'Plus productif avec une pollinisation croisée. Massif, isolé, haie, potager. Comestible, fixateur d’azote, médicinale (régule taux cholestérol), mellifère. Fruits : en été, rouge vif, pulpe sucrée', 'protéger les fruits des oiseaux. Rabattre d’un tiers les rameaux ayant fructifié', NULL, NULL, ''),
(137, 'fruitier', 'CARISSA macrocarpa (Prunier du Natal)', 'img\\imgBDD\\PrunierNatal.png', 'blanc de mai à septembre', 'vert', 3, 3, NULL, NULL, 'persistant', 'soleil, tolère mi-ombre', 'riche, frais, drainé et profond, tolère le sec en été', NULL, NULL, '-5°C', 'isolé, haie, pot. Fruit comestible. Fruits : ovales, charnus, rouge rosé. Attention les graines sont toxiques.', NULL, 'grandes épines', 'longue floraison parfumée, mellifère', ''),
(138, 'fruitier', 'PRUNUS tomentosum (Ragouminier, cerisier de Nankin)', 'img\\imgBDD\\Ragouminier.png', NULL, 'vert puis jaune', 2, 2, NULL, NULL, 'caduc', 'soleil', 'drainé', NULL, NULL, '-20°C', 'isolé, haie, verger. Fruits : en été ils ressemblent à des cerises sans queues', 'pailler l’été, ajouter du compost au pied chaque automne', NULL, 'mellifère', ''),
(139, 'fruitier', 'HIPPOPHAE rhamnoides \'Friesdorfer orange\' (Argousier)', 'img\\imgBDD\\Argousier.png', NULL, 'vert bleuté puis jaune', 3, 5, NULL, NULL, 'caduc', 'soleil', 'tous, drainé', 'touffe buissonnante', NULL, NULL, 'haie, massif, talus, isolé. Fruits comestibles, plante mellifère, fixatrice d’azote, stabilisatrice de sols\r\nFruits : baies oranges pratiquement sans noyau, pulpe juteuse. Excellente variété fruitière, autofertile et peu épineuse.', 'limiter le drageonnement ', NULL, NULL, ''),
(140, 'fruitier', 'ACTINIDIA arguta Ananasnaya (femelle) (KIWAÏ)', 'img\\imgBDD\\argutaAnanasnaya.png', NULL, NULL, 5, 5, 'septembre', NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé, acide', NULL, NULL, NULL, 'haie palissée, grimpante. Fruit : fruit vert, chair verte, 3 cm, peau lisse', 'tailler en fin d’hiver', NULL, 'excellent goût, doux et sucré', ''),
(141, 'fruitier', 'ACTINIDIA arguta Issaï (autofertile) (KIWAÏ)', 'img\\imgBDD\\argutaIssai.png', NULL, NULL, NULL, NULL, 'septembre', NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé, acide', NULL, NULL, NULL, 'haie palissée, grimpante. Fruit : fruit vert, chair verte, 3 cm, peau lisse', 'tailler en fin d’hiver', NULL, NULL, ''),
(142, 'fruitier', 'ACTINIDIA arguta Ken\'s red (femelle) (KIWAÏ)', 'img\\imgBDD\\argutaKensred.png', NULL, NULL, 5, 5, 'septembre', NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé, acide', NULL, NULL, NULL, 'haie palissée, grimpante. Fruit : peau et chair pourpre, 3 cm, peau lisse', 'tailler en fin d’hiver', NULL, NULL, ''),
(143, 'fruitier', 'ACTINIDIA arguta Weiki (mâle) (KIWAÏ)', 'img\\imgBDD\\argutaWeiki.png', NULL, NULL, 5, 5, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé, acide', NULL, NULL, NULL, 'haie palissée, grimpante', 'tailler en fin d’hiver', NULL, NULL, ''),
(144, 'fruitier', 'Aronia prunifolia (Aronie noire compacte)', 'img\\imgBDD\\Aronienoirecompacte.png', 'blanche', 'vert puis orange bronze', 2, 1, 'fin printemps', NULL, 'caduc', 'soleil, mi-ombre', 'humifère, drainé, non calcaire', 'érigée', NULL, NULL, 'au potager, massif d’arbustes, isolé, bac. Fruits comestibles et médicinaux', 'éliminer les vieux bois et éclaircir les drageons pour limiter son expansion et favoriser sa fructification', NULL, 'mellifère', ''),
(145, 'fruitier', 'ELAEAGNUS umbellata POINTILLA® AMOROSO® (Goumi du Japon )', 'img\\imgBDD\\GoumiduJapon.png', 'Fruit : rouge, sucré. Productif, sept-oct', 'vert puis jaune', 3, 2, 'fin printemps', NULL, 'semi-persistant', 'soleil, ombre légère', 'sec, calcaire', 'divergente', NULL, NULL, 'haie, alignement,  massif d’arbustes, isolé. Fruits comestibles et médicinaux. Fixateur d’azote', 'tailler après la fructification afin de réduire ses branches.', NULL, 'floraison parfumée, mellifère et nectarifère.', ''),
(146, 'fruitier', 'SCHISANDRA chinensis (Baie de Chine aux 5 saveurs)', 'img\\imgBDD\\SCHISANDRA.jpg', NULL, 'vert', 10, NULL, 'août à octobre', NULL, 'caduc', 'soleil, ombre légère', 'riche et frais, pas de calcaire', 'grimpante', NULL, NULL, 'Condimentaire, médicinale. Treillis, pergola. Forêt comestible. Espèce dioïque dont la détermination sexuelle n’est pas faîte à ce stade. Il est conseillé de prendre 2 à 3 plants pour être sûr d’avoir des pieds mâles et femelles.\r\nFruit : rouge, moyen à gros, en grappes mûrs entre août et octobre', NULL, NULL, NULL, ''),
(147, 'fruitier', 'LONICERA caerulea \'Kamtschatica\' (Baie de mai, chèvrefeuille comestible, camérisier)', 'img\\imgBDD\\Baiemai.png', 'jaune clair', 'vert puis jaune', 2, NULL, 'mars - avril', NULL, 'caduc', 'soleil, ombre légère', 'frais, humifère, non calcaire', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Fruits comestibles (nature, séché, congelé, confiture) et médicinaux', 'rustique. Tailler après la fructification pour supprimer des branches trop frêles et diminuer des rameaux de l\'année afin de favoriser l\'éclatement des bourgeons de l\'année. Pailler pour maintenir sol frais.', NULL, 'floraison parfumée, mellifère', ''),
(148, 'fruitier', 'RIBES nigrum (cassis)', 'img\\imgBDD\\cassis.png', 'rosé', 'vert', 2, 1, 'fin printemps', NULL, 'caduc', 'mi-ombre', 'frais, humifère, acide, non calcaire, argileuse', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé, bordure, potager\r\nFruit comestible et médicinal', 'tailler court les vieux bois pour maintenir le maximum de jeunes rameaux de un ou deux ans.', NULL, 'mellifère', ''),
(149, 'fruitier', 'RIBES rubrum (groseiller blanc)', 'img\\imgBDD\\groseillerblanc.png', NULL, 'vert', 2, 1, 'fin printemps', NULL, 'caduc', 'mi-ombre', 'humifère, non calcaire, argileuse', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé, potager\r\nFruit comestible et médicinal', 'tailler les tiges de quatre à cinq ans au raz du sol. Aérer l\'arbuste régulièrement et supprimer les vieux bois morts au centre de la touffe ', NULL, 'mellifère', ''),
(150, 'fruitier', 'RIBES uva-crispa (Groseillier à maquereau rouge)', 'img\\imgBDD\\Groseilliermaquereaurouge.png', 'rose', 'vert', 2, 1, 'fin printemps', NULL, 'caduc', 'mi-ombre', 'humifère, non calcaire, argileuse', 'divergente', NULL, NULL, 'massif d’arbustes, isolé, bordure, potager', 'La taille du Groseillier à maquereau rouge se limite à la suppression des branches les plus âgées. Résistant à l\'oïdium', NULL, 'mellifère', ''),
(151, 'fruitier', 'RIBES nidigrolaria \'JostaBerry\' (Caseille Josta) ', 'img\\imgBDD\\CaseilleJosta.png', 'rose-orangé', 'vert', 2, 1, 'fin printemps', NULL, 'caduc', 'mi-ombre', 'frais, humifère, acide, non calcaire, argileuse', 'buissonnante', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Comestible et médicinal', 'tailler court les vieux bois. La Casseille est plus grosse que le Cassis mais moins colorée.', NULL, 'variété vigoureuse, résistante à l’oïdium, rouille ou anthracnose. Mellifère', ''),
(152, 'fruitier', 'VITIS \'Boskoop Glory\' (Raisin de table)', 'img\\imgBDD\\BoskoopGlory.png', NULL, 'vert puis jaune-orangé', 5, 5, 'fin printemps', NULL, 'caduc', 'soleil', 'humifère, sèche, calcaire', 'grimpante', NULL, NULL, 'haie palissée, isolé, grimpante', 'tailler en hiver pour éliminer les sarments ayant fructifié et au début du printemps à 3 ou 4 yeux pour favoriser la montée de sève. ', NULL, 'Résistante aux maladies fongiques.', ''),
(153, 'fruitier', 'VITIS \'Vroege van der Laan\' (Vigne de table)', 'img\\imgBDD\\Vignetable.png', NULL, 'vert puis jaune-orangé', 5, 10, 'fin printemps', NULL, 'caduc', 'soleil', 'humifère, sèche, calcaire', 'grimpante', NULL, NULL, 'haie palissée, isolé, grimpante', 'tailler en hiver pour éliminer les sarments ayant fructifié et au début du printemps à 2 ou 3 yeux pour favoriser la montée de sève. Adaptée au Nord de la Loire', NULL, 'Résistante aux maladies fongiques.', ''),
(154, 'fruitier', 'Pêche de vigne jaune (Prunus persica)', 'img\\imgBDD\\Prunuspersica.png', 'rose', 'vert', 3, 2, 'début printemps', NULL, 'caduc', 'soleil', 'bonne terre, non calcaire, drainé', 'érigée', NULL, NULL, 'haie palissée, isolé', 'tailler chaque année pour renouveler les branches de l’année porteuses de fruits', 'résiste aux froids de l\'hiver mais sa floraison précoce peut être détruite par les gelées printanières.', NULL, ''),
(155, 'fruitier', 'Pêche de vigne blanche (Prunus persica)', 'img\\imgBDD\\Prunuspersicablanc.png', 'rose', 'vert', 3, 2, 'début printemps', NULL, 'caduc', 'soleil', 'bonne terre, non calcaire, drainé', 'érigée', NULL, NULL, 'haie palissée, isolé', 'tailler chaque année pour renouveler les branches de l’année porteuses de fruits', 'résiste aux froids de l\'hiver mais sa floraison précoce peut être détruite par les gelées printanières.', NULL, ''),
(156, 'fruitier', 'PUNICA granatum (Grenadier)', 'img\\imgBDD\\Grenadier.png', 'rouge-orangé', 'vert', 5, NULL, 'mai-juillet', NULL, NULL, 'soleil', 'fertile, frais, drainé', 'arrondie', NULL, NULL, 'isolé', NULL, NULL, NULL, ''),
(157, 'fruitier', 'FUCHSIA regia ssp Reitzii (Fuschia royal)', 'img\\imgBDD\\Fuschiaroyal.png', 'bicolore rouge/violet', 'vert', 2, 2, 'juillet-novembre', NULL, 'caduc à semi-persistant', 'soleil, mi-ombre, ombre', 'frais, humifère, drainé, acide', 'touffe buissonnante', NULL, NULL, 'massif d\'arbustes, massif de vivaces, isolé, bac, forêt-comestible. Fruits bleu foncé de la taille d’une cerise à consommer frais ou confiture.', 'tailler après la récolte. Cette taille consiste à supprimer le vieux bois en laissant 2 ou 3 yeux et à éliminer les tiges en surnombre.', NULL, 'mellifère', ''),
(158, 'fruitier', 'HIPPOPHAE rhamnoides (Argousier)', 'img\\imgBDD\\HIPPOPHAErhamnoides.png', NULL, 'gris-vert', 4, 5, NULL, NULL, 'caduc', 'soleil', 'frais, drainé', 'touffe buissonnante', NULL, NULL, 'fruits comestibles, oranges et juteux en grappe en fin d’été. Plante mellifère, fixatrice d’azote', 'limiter le drageonnement important', NULL, NULL, ''),
(159, 'fruitier', 'CORYLUS maxima \'Purpurea\' (Noisetier pourpre)', 'img\\imgBDD\\Noisetierpourpre.png', NULL, 'pourpre', 6, 5, 'février-mars', NULL, 'persistant', 'soleil', 'pas trop sec à frais', 'touffe dressée', NULL, NULL, 'haie, isolé, comestible', 'tailler après floraison', NULL, NULL, ''),
(160, 'fruitier', 'ARONIA arbutifolia Brillant (Aronie à feuille d\'arbousier)', 'img\\imgBDD\\arbutifoliaBrillant.png', NULL, 'vert puis rouge', 3, 2, 'mai-juin, sept-nov', NULL, 'caduc', 'soleil, mi-ombre', 'frais à humide, drainé', NULL, NULL, NULL, 'arbuste décoratif, mellifère aux fruits comestibles. Fruits sucrés, légèrement acidulés à consommer en jus, confiture, ou en accompagnement. Riches en vitamine C et antioxydants.', 'tailler après floraison', NULL, 'mellifère', ''),
(161, 'fruitier', 'CASTANEA sativa (Châtaigner commun)', 'img\\imgBDD\\Chataignercommun.png', NULL, 'vert', 30, 15, 'été', NULL, 'caduc', 'soleil', 'acide à neutre, pas de calcaire, frais, profond, pauvre, drainé', 'touffe buissonnante', NULL, NULL, 'boisement ou isolé. Les fruits se consomment bouillis, grillés ou sous forme de farine. Arbre de croissance rapide', 'limité', NULL, 'mellifère, bois de bonne qualité', ''),
(162, 'fruitier', 'CHAENOMELES japonica Cido (Cognassier du Japon fruitier)', 'img\\imgBDD\\CognassierJaponfruitier.png', 'orange', 'vert puis jaune', 1, 1, '', NULL, 'caduc', 'soleil partiel, ombre légère', 'bonne terre de jardin, non calcaire', 'touffe buissonnante', NULL, NULL, 'haie, isolé, bac, sur balcon. Les fruits, bien qu’acides, sont délicieux. Idéal pour boissons, sirops, confitures. Floraison ornementale. ', 'limité', NULL, NULL, ''),
(163, 'fruitier', 'CYDONIA vulgaris Vranja (Cognassier à gros fruit)', 'img\\imgBDD\\Cognassiergrosfruit.png', 'blanc-rosé', 'vert puis jaune', 5, 3, 'avril', NULL, 'caduc', 'plein soleil', 'bonne terre de jardin, fraîche à humide, non calcaire', 'touffe arrondie', NULL, NULL, 'haie, massif d’arbustes, isolé, comestible généralement cuit, médicinal', 'nécessite peu de taille, un peu de compost', NULL, 'mellifère', ''),
(164, 'fruitier', 'SAMBUCUS nigra Korsor (Sureau à gros fruits)', 'img\\imgBDD\\Sureaugrosfruits.png', NULL, 'vert puis jaune', 5, 3, 'mai-juin, sept-nov', NULL, 'caduc', 'soleil partiel, ombre légère', 'bonne terre de jardin, calcaire, argileuse', NULL, NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Arbuste parfumé et mellifère aux fruits et fleurs comestibles, médicinal ', 'limité. Peut être recépé tous les 2 à 4 ans', NULL, 'repousse naturellement les pucerons et les insectes nuisibles', ''),
(165, 'fruitier', 'RUBUS arcticus Beata (Framboisier arctique)', 'img\\imgBDD\\Framboisierarctique.png', NULL, 'vert', 0, 0, 'avril-juin puis septembre', NULL, 'caduc', 'soleil', 'humifère, drainante, acide, non calcaire', 'couvre-sol', NULL, NULL, 'massif, rocaille, bac, bordures. Les fruits se consomment frais, en jus, en confiture', 'limité, aucune taille', NULL, 'floraison ornementale, mellifère', ''),
(166, 'fruitier', 'RUBUS xanthocarpus (Ronce à fruits jaunes)', 'img\\imgBDD\\Roncefruitsjaunes.png', 'blanc', 'vert puis jaune', 1, 1, NULL, NULL, 'caduc', 'soleil', 'bonne terre, drainée, calcaire, fraîche à humide', 'rampante, couvre-sol', NULL, NULL, 'palissé, isolé, grimpante, au potager. Fruits d’été sucrés et acidulés', 'tailler le vieux bois après fructification et conserver les jeunes pousses', NULL, 'mellifère', ''),
(167, 'fruitier', 'SORBUS torminalis (Alisier torminal)', 'img\\imgBDD\\Alisiertorminal.png', 'blanc', 'vert puis rouge, orange, jaune', 10, 7, 'avril', NULL, 'caduc', 'soleil partiel, ombre légère', 'fraîche à humide, légère, acide', 'érigée', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Fruits comestibles automne', 'ne nécessite aucune taille', NULL, 'mellifère', ''),
(168, 'fruitier', 'CORYLUS maxima Purpurea (Noisetier pourpre)', 'img\\imgBDD\\Noisetierpourpre2.png', NULL, 'pourpre puis orange', 5, 3, 'mai-juin, sept-nov', NULL, 'caduc', 'soleil partiel, ombre légère', 'bonne terre de jardin, sèche, calcaire', 'érigée', NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Fruits d’automne', 'aucun', NULL, 'les piquets/perches obtenus par recépage sont utiles mais empêchent la fructification. Feuilles = médicinales', ''),
(169, 'fruitier', 'ELAEAGNUS umbellata (Chalef d’automne)', 'img\\imgBDD\\Chalefautomne.png', 'crème', 'vert, revers argenté', 4, 3, 'mai', NULL, 'caduc', 'soleil, mi-ombre', 'souple, bien travaillé. Supporte calcaire, sec, vent', 'touffe buissonnante', NULL, NULL, 'haies champêtre, brise-vent ou fruitière. Fruit utilisé cru, compote ou confiture, sucré et acidulé, riche en vitamines et antioxydants', 'traille de formation les premières années à la sortie de l’hiver', NULL, 'très bon fixateur d’azote, mellifère, nectarifère', ''),
(170, 'fruitier', 'Asiminier, Paw paw (Asiminia triloba)', 'img\\imgBDD\\Asiminiatriloba.png', 'violette', 'vert', 4, 3, 'avril-mai', NULL, 'caduc', 'soleil mi-ombre', 'humide l’été, bonne terre de jardin, bien drainé, riche.', 'touffe érigée', NULL, NULL, 'isolé', 'pailler l’été et prévoir une protection hivernale les premières années', NULL, NULL, ''),
(171, 'fruitier', 'Poivre du Sichuan (ZANTHOXYLUM piperitum)', 'img\\imgBDD\\ZANTHOXYLUM.png', 'jaune verdâtre', 'vert', 2, 2, 'avril-mai', NULL, 'caduc', 'plein soleil', 'fertile, drainé', 'touffe buissonnante', NULL, NULL, 'massif, bac, potager, isolé, haie libre, haie défensive', 'pailler le pied en été. Taille annuelle car fleurit sur les rameaux de l’année précédente', NULL, 'on utilise également les feuilles et l’écorce en cuisine. utilisé en phytothérapie', ''),
(172, 'fruitier', 'Figuier Goutte d\'Or (FICUS carica)', 'img\\imgBDD\\FICUScarica.png', NULL, NULL, 3, 2, NULL, NULL, 'caduc', 'soleil', 'tous les sols, plutôt calcaires, bien drainés', 'buissonnante', NULL, NULL, 'faible développement, parfait pour une culture en pot ou pour de petits espaces, massif, haie libre, petit jardin, isolé', 'taille facultative en début d’hiver uniquement en climat doux. Supprimer les plus vieilles branches et celles qui se croisent, aérer le centre. Supprimer les rejets au pied ', NULL, NULL, ''),
(173, 'fruitier', 'Pacanier, Noix de pécan (CARYA illinoinensis)', 'img\\imgBDD\\CARYAillinoinensis.png', NULL, 'vert', 40, 8, NULL, NULL, 'caduc', 'plein soleil', 'riche, frais et bien drainé', 'touffe arrondie', NULL, NULL, 'isolé, bosquet, pour les grands jardins', 'pailler le pied toute l’année. Pas de taille', NULL, NULL, ''),
(174, 'fruitier', 'Arbousier, Arbre aux fraises (ARBUTUS unedo)', 'img\\imgBDD\\ARBUTUSunedo.png', 'blanches', 'vert', 5, 4, 'fin automne', NULL, 'persistant', 'plein soleil, à l’abri des vents froids', 'tous, bien drainé', 'touffe érigée', NULL, NULL, 'isolé, massif d’arbustes, haie', 'pailler le pied avant l’hiver, pas de taille nécessaire', NULL, 'mellifère', ''),
(175, 'fruitier', 'Framboisier remontant  (RUBUS ideaus \'Héritage\')', 'img\\imgBDD\\RUBUSideaus.png', NULL, NULL, 2, 1, NULL, NULL, NULL, 'mi-ombre', 'humide l’été, humifère, bien drainé, non calcaire', NULL, NULL, NULL, 'en alignement, au potager', 'pailler en été. \r\nTaille d’hiver : tailler les tiges ayant fructifié en fin d’été juste en dessous de la partie ayant porté des fruits, conserver maximum 7 à 8 tiges vigoureuses. Taille d’été : après la récolte supprimer les tiges ayant porté des fruits. Supprimer les rejets pour limiter son expansion.', NULL, NULL, ''),
(176, 'fruitier', 'Kiwi Boskoop (ACTINIDIA deliciosa \'Boskoop\')', 'img\\imgBDD\\ACTINIDIAdeliciosa.png', 'jaune verdâtre', 'vert puis jaune', 10, 6, 'avril-mai', NULL, 'caduc', 'plein soleil, protégé du froid', 'humide l’été, riche, drainé, plutôt acide', 'grimpante', NULL, NULL, NULL, 'pailler le pied en été, palisser à mesure du développement. Taille d’été : tailler à environ 4 feuilles au dessus des derniers fruits, supprimer les gourmands. Tous les 3-4 ans, rajeunir les branches fructifères en fin d’hiver en les rabattant à 50cm de la base. Taille d’hiver : tailler à 2 yeux au dessus du dernier fruit récolté', NULL, 'idéal pour couvrir une tonnelle ou terrasse', ''),
(177, 'fruitier', 'Olivier commun (OLEA europea)', 'img\\imgBDD\\OLEAeuropea.png', NULL, 'gris-vert ', 5, 5, NULL, NULL, 'persistant', 'soleil', 'bien drainé, calcaire et sec', 'touffe arrondie', NULL, NULL, 'isolé, bac, massif', 'taille d’entretien au printemps. Supprimer les vieilles branches, celles qui se croisent, aérer le centre', NULL, NULL, ''),
(178, 'fruitier', 'Raisin du Japon, mûre japonaise (RUBUS phoenicolasius)', 'img\\imgBDD\\RUBUSphoenicolasius.png', NULL, NULL, 3, 3, NULL, NULL, 'caduc', 'plein soleil', 'frais, fertile', 'touffe buissonnante', NULL, NULL, 'en alignement, au potager, en massif, en haie défensive, comme grimpante à palisser', 'contrôler son développement par une taille régulière, un arrachage des rejets et un palissage régulier. Après la récolte supprimer les branches ayant porté des fruits, conserver maximum 7 à 8 tiges vigoureuses.', NULL, 'mellifère', ''),
(179, 'fruitier', 'SAMBUCUS nigra (Sureau à gros fruits)', 'img\\imgBDD\\SAMBUCUSnigra.png', NULL, 'vert puis jaune', 5, 3, 'mai-juin, sept-nov', NULL, 'caduc', 'soleil partiel, ombre légère', 'bonne terre de jardin, calcaire, argileuse', NULL, NULL, NULL, 'haie, alignement, massif d’arbustes, isolé. Arbuste parfumé et mellifère aux fruits et fleurs comestibles, médicinal', 'limité. Peut être recépé tous les 2 à 4 ans', NULL, 'repousse naturellement les pucerons et les insectes nuisibles', ''),
(180, 'fruitier', 'AKEBIA quinata (Liane chocolat)', 'img\\imgBDD\\AKEBIAquinata.png', 'mauve', 'vert', 10, 5, NULL, NULL, 'semi-persistant', 'soleil, tolère mi-ombre', 'riche, drainé', NULL, NULL, '- 15 °C', 'palissée, pergola. Fruits et jeunes pousses comestibles', 'fleurit sur les rameaux de l’année précédente. Protéger le pied en hiver. ', NULL, 'floraison parfumée, nectarifère', ''),
(181, 'fruitier', 'CORYLUS avellana \'Merveille de Bollwiller\' (Noisetier)', 'img\\imgBDD\\Noisetier.png', NULL, 'vert puis jaune', 3, 2, NULL, NULL, 'caduc', 'soleil', 'drainé, pas trop sec', NULL, NULL, '-14°C', 'massif, haie, isolé. Fruit comestible, excellent pollinisateur', 'en hiver griffer le sol pour que les oiseaux éliminent les nuisibles. Tailler tous les 3-4 ans en aérant le centre', NULL, NULL, ''),
(182, 'fruitier', 'MYRTHUS ugni (Myrte, Goyavier du Chili)', 'img\\imgBDD\\GoyavierChili.png', NULL, 'vert', 2, 1, NULL, NULL, 'persistant', 'soleil', 'fertile, frais, drainé, acide', NULL, NULL, '-7°C', 'potager, jardin d’hiver, haie, massif, bac. Fruit comestible, feuilles en infusion', 'protection hivernale si besoin', NULL, 'parfumé, mellifère, nectarifère', ''),
(183, 'fruitier', 'RIBES rubrum (groseiller rouge)', 'img\\imgBDD\\groseillerrouge.png', NULL, 'vert', 2, 1, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'humifère, frais, non calcaire', NULL, NULL, '-15°C', 'haie, alignement, massif d’arbustes, isolé, potager', 'tailler les tiges de quatre à cinq ans au raz du sol. Aérer l\'arbuste régulièrement et supprimer les vieux bois morts au centre de la touffe ', NULL, 'mellifère', ''),
(184, 'fruitier', 'MESPILUS germanica (Néflier commun)', 'img\\imgBDD\\Nefliercommun.png', NULL, 'vert', 6, 5, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'drainant, supporte le calcaire', NULL, NULL, '-20°C', 'isolé, verger, haie', NULL, NULL, NULL, ''),
(185, 'fruitier', 'RUBUS fruticosus \'Géante\' (Mûre géante sans épines)', 'img\\imgBDD\\RUBUSfruticosus.png', NULL, 'vert', 3, 2, NULL, NULL, 'caduc', 'soleil', NULL, NULL, NULL, '-14°C', NULL, 'palisser, supprimer les rejets pour limiter son expansion, après récolte supprimer les branches ayant donné', NULL, 'nectarifère', ''),
(186, 'fruitier', 'AMELANCHIER canadensis (Amélanchier)', 'img\\imgBDD\\Amelanchier.png', 'blanche en avril-mai', 'vert puis rouge', 10, 3, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'frais, riche, éviter le calcaire et les sols séchants', NULL, NULL, '- 15 °C', 'isolé, massif, haie. Fruits comestibles : petites baies, en été', NULL, NULL, NULL, ''),
(187, 'fruitier', 'VITIS vinifera \'Chardonnay\' (Raisin de table blanc)', 'img\\imgBDD\\Chardonnay.png', NULL, 'vert', 3, 3, NULL, NULL, 'caduc', 'soleil', 'argilo-calcaire', NULL, NULL, '- 15 °C', 'isolé, grimpante à palisser. Fruit : blanc, sucré, aromatique, utilisé pour la vinification et le raisin de table', 'en hiver supprimer les sarments ayant fructifié, tailler les sarments vigoureux à 3 ou 4 yeux pour favoriser la montée de sève ', NULL, 'Résistant au phylloxera', ''),
(188, 'fruitier', 'ROSA rugosa rubra (Rosier rugueux, rosier du Japon)', 'img\\imgBDD\\Rosierrugueux.png', 'rouge', 'vert', 2, 2, 'mai-sept', NULL, 'caduc', 'soleil', 'frais, bien drainé', NULL, NULL, '-15°C', 'haie, massif, isolé. Fruit : comestible et médicinal, en hiver', 'taille légère en mars et apport de compost au pied', NULL, 'fleur parfumée', ''),
(189, 'fruitier', 'ROSA rugosa alba (Rosier rugueux, rosier du Japon)', 'img\\imgBDD\\Rosierrugueuxblanc.png', 'blanche', 'vert', 2, 2, 'mai-sept', NULL, 'caduc', 'soleil', 'frais, bien drainé', NULL, NULL, '-15°C', 'haie, massif, isolé. Fruit : comestible et médicinal, en hiver', 'taille légère en mars et apport de compost au pied', NULL, 'fleur parfumée', ''),
(190, 'fruitier', 'Feijoa sellowiana (Goyavier de Montevideo)', 'img\\imgBDD\\Feijoasellowiana.png', NULL, NULL, 10, NULL, 'spectaculaire, mai-juillet', NULL, 'persistant ', 'soleil, abrité des vents forts', 'tous, drainé', 'arbre', NULL, NULL, 'saveur acidulée rappelant la fraise, l\'ananas ou la goyave. Fruits : verts, de la taille d\'un kiwi', 'résiste jusqu\'à – 10°C, arroser l\'été + paillage au pied. Pollinisation croisée, planter par deux.', NULL, NULL, ''),
(191, 'fruitier', 'Lycium barbarum (Lyciet, Goji)', 'img\\imgBDD\\Lyciumbarbarum.png', NULL, NULL, 3, NULL, NULL, NULL, 'caduc', 'soleil, mi-ombre', 'sec, bien drainé', 'buissonnante', NULL, NULL, 'séché ou en jus. Propriétés médicinales : le goji permettrait de renforcer les défenses immunitaires de faire baisser la tension artérielle, le taux de cholestérol et de sucres dans le sang, d’améliorer l’assimilation du calcium et de soulager le foie. Fruits : petits, rouges', 'tailler les 2 premières années pour ramifier l\'arbuste.', NULL, NULL, ''),
(192, 'graminée', 'LUZULA nivea (Luzule blanche)', 'img\\imgBDD\\Luzuleblanche.png', 'blanc', 'vert', 0, NULL, 'juin-août', NULL, 'persistant', 'mi-ombre, ombre', 'frais, humifère', 'touffé dressée', '8 au m²', NULL, 'couvre-sol des sous-bois', 'Pratiquement sans entretien. Couper les parties sèches et nettoyer les touffes en fin d\'hiver, si nécessaire.', NULL, 'tolère la sécheresse', ''),
(193, 'graminée', 'Festuca glauca (fétuque bleue)', 'img\\imgBDD\\fetuquebleue.png', NULL, 'bleuté', 0, NULL, 'mai à juillet', NULL, 'persistant', 'soleil', 'sec, profond et drainé', 'touffe buissonnante', '9 au m²', NULL, 'rocaille, jardin sur gravier, petit couvre-sol', 'tondre ou tailler les parties sèches avant le démarrage de la végétation au printemps. Le coloris sera plus intense et la longévité sera favorisée. Si la touffe se dégarnie au centre, diviser puis replanter au début du printemps. ', NULL, NULL, ''),
(194, 'vivace', 'TEUCRIUM chamaedrys (Germandrée petit chêne)', 'img\\imgBDD\\Germandreepetitchene.png', 'rose', 'vert foncé', 0, NULL, 'juin-octobre', NULL, 'persistant', 'soleil, ombre', 'sec, supporte les sols calcaires', 'touffe étalée', '6 au m²', NULL, 'bordures basses, rocaille, couvre-sol', 'Couper les inflorescences fanées en réduisant largement le feuillage pour prolonger les floraisons. Tailler en fin d\'hiver afin de conserver une touffe compacte', NULL, 'Supporte bien la concurrence racinaire en lisère de bois de pins ou de chênes', ''),
(195, 'vivace', 'OENOTHERA odorata (Onagre odorante)', 'img\\imgBDD\\Onagreodorante.png', 'jaune crême', 'vert', 1, NULL, 'juin-octobre', NULL, 'caduc', 'soleil, mi-ombre', 'sec et frais', 'touffe buissonnante', '6 au m²', NULL, 'massif de vivaces', 'Couper les fleurs fanées et raccourcir les tiges pour prolonger les floraisons. Rabattre les parties sèches dès qu\'elles ne sont plus décoratives et au plus tard en fin d\'hiver', NULL, 'odorante', ''),
(196, 'vivace', 'SALVIA (sauge violet clair)', 'img\\imgBDD\\SALVIA.png', 'violet clair', 'vert', 1, NULL, 'juillet-novembre', NULL, 'caduc', 'soleil', 'tous', 'touffe buissonnante', '3 au m²', NULL, 'massif, bac', 'Couper les inflorescences fanées pour prolonger les floraisons en pinçant le feuillage. Tailler en fin d\'hiver et éliminer les tiges en surnombre', NULL, 'culture facile', ''),
(197, 'vivace', 'SALVIA (sauge violet foncé)', 'img\\imgBDD\\saugevioletfonce.png', 'violet foncé', 'vert', 1, NULL, 'juillet-novembre', '', 'caduc', 'soleil', 'tous', 'touffe buissonnante', '3 au m²', NULL, 'massif, bac', 'Couper les inflorescences fanées pour prolonger les floraisons en pinçant le feuillage. Tailler en fin d\'hiver et éliminer les tiges en surnombre', NULL, 'culture facile', ''),
(198, 'vivace', 'ECHINOPS bannaticus \'Star Frost\' (boule azurée)', 'img\\imgBDD\\bouleazuree.png', 'blanc argenté', 'vert', 1, NULL, 'juillet-septembre', NULL, 'caduc', 'soleil', 'sec, supporte le calcaire', 'touffe dressée', '6 au m²', NULL, 'massif de vivaces, intéressantes en fleurs coupées et en bouquets secs.', 'supprimer les inflorescences fanées pour prolonger les floraisons mais conserver celles de fin de saison qui, sèches, resteront belles longtemps. Tailler lorsqu\'elles ne sont plus décoratives. Nettoyer la touffe au plus tard au redémarrage de la végétation.', NULL, NULL, ''),
(199, 'vivace', 'OSTEOSPERMUM fruticosum (Marguerite du Cap)', 'img\\imgBDD\\MargueriteCap.png', 'violet', 'vert', 0, NULL, 'mai à octobre', NULL, 'persistant', 'soleil', 'léger, bien drainé, supporte le calcaire. Sec', 'touffe étalée', '6 au m²', NULL, 'bac, muret, couvre-sol en climat doux', 'Supprimer les inflorescences fanées pour prolonger les floraisons.', 'rustique jusqu\'à -5 °C. Placer contre un mur bien orienté, protéger l\'hiver ou la considérer comme annuelle.', NULL, ''),
(200, 'vivace', 'LAVANDULA pinnata (Lavande des Canaries)', 'img\\imgBDD\\LavandeCanaries.png', 'bleu', 'vert grisé', 1, NULL, 'mars à octobre', NULL, 'persistant', 'soleil', 'léger, bien drainé. Sec', 'touffe dressée', '2-3 au m²', NULL, 'jardin sur gravier, massif de vivaces, bac', 'Supprimer les inflorescences fanées pour prolonger les floraisons.', 'rustique jusqu\'à -5 °C. Protéger du froid', NULL, ''),
(201, 'vivace', 'EUPHORBIA myrsinites (Euphorbe de Corse)', 'img\\imgBDD\\EuphorbeCorse.png', 'jaune verdâtre', 'bleuté', 0, NULL, 'mars à juin', NULL, 'persistant', 'soleil ou mi-ombre', 'léger, bien drainé. Sec. Supporte le calcaire', 'touffe étalée', '6 au m²', NULL, 'rocaille, jardin sur gravier, toitures végétalisées. Couvre-sol', 'Pratiquement sans entretien. Couper les inflorescences fanées dès qu\'elles ne sont plus décoratives et raccourcir les tiges si la touffe se dégarnit', NULL, 'supporte la concurrence racinaire au pied des arbres caducs', ''),
(202, 'vivace', 'ARMERIA Ps. Ballerina Mix (Gazon d\'Espagne)', 'img\\imgBDD\\GazonEspagne.png', 'blanc, rose, rouge', 'vert', 0, NULL, 'avril-août', NULL, 'persistant', 'soleil, mi-ombre', 'pauvre, bien drainé, sec', 'coussin', '9 au m²', NULL, 'rocaille, bordure de massif', 'supprimer les fleurs fanées pour prolonger les floraisons. L\'hiver, diviser ou compléter les petites touffes pour replanter les trous, si besoin.', NULL, NULL, ''),
(203, 'vivace', 'SALVIA lavandulifolia (Sauge à feuille de lavande)', 'img\\imgBDD\\SALVIAlavandulifolia.png', 'bleu', 'gris-argenté', 0, NULL, 'juin-juillet', NULL, 'persistant', 'soleil', 'pauvre, parfaitement drainé, sec. Supporte le calcaire', 'touffe arrondie', '5 au m²', NULL, 'massif de vivaces, couvre-sol, jardin aromatique', 'Couper les inflorescences fanées. Taillez en fin d\'hiver pour conserver une touffe compacte.', NULL, NULL, ''),
(204, 'vivace', 'JOVIBARBA sobolifera (Barbe de Jupiter, Joubarbe)', 'img\\imgBDD\\BarbeJupiter.png', 'jaune', 'vert', 0, NULL, 'juin-juillet', NULL, 'persistant', 'soleil', 'pauvre, drainé, sec', 'rosette', '15 au m²', NULL, 'couronne de muret, rocaille, toiture végétale', 'pratiquement sans entretien. Supprimer la rosette qui sèche après floraison pour favoriser la formation de nouveaux rejets.', NULL, NULL, ''),
(205, 'vivace', 'POTENTILLA nepalensis (Potentille du Népal)', 'img\\imgBDD\\PotentilleNepal.png', 'rose, saumon', 'vert', 1, NULL, 'avril-octobre', NULL, 'caduc', 'soleil', 'sec et frais, bien drainé', 'touffe étalée', '6 au m²', NULL, 'bordure de massif', 'couper les inflorescences fanées à la base des tiges florales pour prolonger les floraisons. Rabattre les tiges sèches en fin d\'hiver.', NULL, NULL, ''),
(206, 'vivace', 'KNIPHOFIA uvaria (Tison de satan)', 'img\\imgBDD\\Tisondesatan.png', 'bicolore', 'bleuté', 1, NULL, 'juin-septembre', NULL, 'persistant', 'soleil', 'léger, riche, sec', 'touffe hérissée', '5 au m²', NULL, 'massif de vivaces', 'couper les fleurs fanées à la base des hampes florales. Nettoyer la touffe, si besoin, avant le démarrage de la végétation au printemps. Protéger d\'un paillis sec en régions très froides.', NULL, 'mellifère', ''),
(207, 'vivace', 'CHAMAEMELUM nobile \'Ligulosum\' (Camomille romaine)', 'img\\imgBDD\\Camomilleromaine2.png', 'blanc', 'vert', 0, NULL, 'juin-août', NULL, 'persistant', 'soleil', 'sec', 'tapissante', '6 au m²', NULL, 'rocaille, bordure de massif. \r\nMédicinale : troubles digestifs, affections dermatologioques', 'couper les fleurs fanées. Rabattre régulièrement les touffes pour maintenir le tapis vert.', NULL, NULL, ''),
(208, 'vivace', 'SOLIDAGO canadensis \'Yellow spring\' (Verge d\'or)', 'img\\imgBDD\\Vergeor.png', 'jaune', 'vert', 1, NULL, 'juillet-septembre', NULL, 'persistant', 'soleil, mi-ombre, ombre', 'sec', 'touffe dressée', '6 au m²', NULL, 'massif de vivaces, fleur à couper', 'supprimer les fleurs fanées pour prolonger les floraisons. ', NULL, 'mellifère', ''),
(209, 'vivace', 'DELPHINIUM pacific Mélange extra (Delphinium)', 'img\\imgBDD\\Delphinium.png', 'blanc, rose ou violet', 'vert', 2, NULL, 'juin-septembre', NULL, 'caduc', 'soleil', 'frais, profond, riche', 'touffe dressée', '4 au m²', NULL, 'massif de vivaces, fleur à couper', 'tailler les hampes fanées pour prolonger les floraisons. Rabattre la touffe en fin d\'automne en apportant un paillage humifère et drainant.', NULL, 'mellifère', ''),
(210, 'vivace', 'CISTUS x pulverulentus \'Sunset\' (ciste \'Sunset\')', 'img\\imgBDD\\Sunset.png', 'rose', 'gris argenté', 2, 1, 'mai-juin', NULL, 'persistant', 'soleil', 'pauvre, drainé, sec, supporte le calcaire', 'touffe arrondie', NULL, NULL, 'talus, massif d’arbustes, jardin allélopathique, j. aromatique', 'tailler après la floraison', NULL, NULL, ''),
(211, 'vivace', 'CISTUS x aguilari', 'img\\imgBDD\\CISTUSxaguilari.png', 'blanc', 'vert foncé', 2, 1, 'avril-mai', NULL, 'persistant', 'soleil ou mi-ombre', 'pauvre, drainé, sec, supporte le calcaire', 'touffe arrondie', NULL, NULL, 'massif d’arbustes, haie libre, jardin aromatique', 'tailler après la floraison', NULL, NULL, ''),
(212, 'vivace', 'CISTUS x ralletii', 'img\\imgBDD\\CISTUSxralletii.png', 'rose', 'vert clair', 1, 1, 'avril-juin', NULL, 'persistant', 'soleil', 'pauvre, drainé, sec, supporte les sols acides, légèrement calcaire', 'touffe arrondie', NULL, NULL, 'massif d’arbustes', 'tailler après la floraison', NULL, NULL, ''),
(213, 'vivace', 'Pelargonium fragans (Géranium odorant)', 'img\\imgBDD\\Geraniumodorant.png', 'blanche', 'vert', 0, NULL, 'mai-octobre', NULL, 'persistant', 'soleil, mi-ombre', 'fertile, frais', NULL, NULL, NULL, 'bordure de massif, potée, jardinière', 'les conserver en serre froide l’hiver', NULL, 'parfum d’eucalyptus', ''),
(214, 'vivace', 'Pelargonium fragans \'variegated\' (Géranium odorant)', 'img\\imgBDD\\Geraniumodorant2.png', 'blanche', 'vert panaché de crème', NULL, NULL, 'mai-octobre', NULL, 'persistant', 'soleil, mi-ombre', 'fertile, frais', NULL, NULL, NULL, 'bordure de massif, potée, jardinière', 'les conserver en serre froide l’hiver', NULL, 'les feuilles dégagent un délicieux parfum ', ''),
(215, 'vivace', 'COSMOS ATROSANGUINEA (Cosmos chocolat)', 'img\\imgBDD\\Cosmoschocolat.png', 'pourpre', 'vert', 1, 0, 'septembre', NULL, 'caduc', 'soleil', 'fertile, drainé', 'touffe étalée', NULL, NULL, 'massif de vivaces, bordure', 'supprimer les fleurs fanées pour prolonger les floraisons. L\'hiver, l’abriter sous un épais paillage. En dessous de -5 C il faut rentrer les souches en silo.', NULL, 'les fleurs ont une bonne odeur de chocolat, et sont comestibles, peuvent décorer les gâteaux...', ''),
(216, 'vivace', 'Aunée orientale (Inula orientalis)', 'img\\imgBDD\\Inulaorientalis.png', 'jaune', 'vert', 1, 1, 'juillet-août', NULL, 'caduc', 'soleil', 'profond, sec', 'rosette', NULL, NULL, 'massifs, fleurs coupées', 'couper les fleurs fanées pour prolonger les floraisons. Rabattre la touffe sèche en fin d\'automne.', NULL, 'mellifère.', ''),
(217, 'vivace', 'Gaura lindheimeri (GAURA lindheimeri \'Siskiyou Pink\')', 'img\\imgBDD\\GAURAlindheimeri.png', 'rose', 'pourpre', 1, 0, 'juin-octobre', NULL, 'caduc', 'soleil, mi-ombre', 'sec et frais', 'touffe buissonnante', NULL, NULL, 'massif de vivaces', 'tailler les hampes fanées en réduisant, si nécessaire, le nombre de tiges. Garder celles de l\'automne qui même sèches resteront décoratives pendant l\'hiver. Rabattre la touffe au plus tard, au démarrage de la végétation.', NULL, NULL, ''),
(218, 'vivace', 'Pennisetum orientale (Herbe aux écuvillons)', 'img\\imgBDD\\Herbeauxecuvillons.png', 'rose', 'vert', 1, 1, 'juillet-septembre', NULL, 'caduc', 'soleil', 'sec et frais, drainé, pauvre', 'touffe buissonnante', NULL, NULL, 'massif de vivaces, bordure, fleur à couper', 'rabattre la touffe au plus tard avant le démarrage de la végétation en fin d\'hiver.', NULL, NULL, ''),
(219, 'vivace', 'Pennisetum alopecuroides (Herbe aux écuvillons)', 'img\\imgBDD\\Herbeauxecuvillon.png', 'brun', 'vert', 1, NULL, 'août-décembre', NULL, 'caduc', 'soleil', 'sec et frais', 'touffe buissonnante', NULL, NULL, 'massif de vivaces', 'rabattre la touffe sèche au plus tard avant le démarrage de la végétation en fin d\'hiver.', NULL, NULL, ''),
(220, 'vivace', 'Pennisetum alopecuroides \'René Guy Cadou\' (Herbe aux écuvillons)', 'img\\imgBDD\\Herbeecuvillonsbrunfonce.png', 'brun foncé devenant beige en fin de saison', 'vert', 1, NULL, 'août-novembre', NULL, 'caduc', 'soleil', 'sec et frais', 'touffe buissonnante', NULL, NULL, 'massif de vivaces', 'rabattre la touffe sèche au plus tard avant le démarrage de la végétation en fin d\'hiver.', NULL, NULL, ''),
(221, 'vivace', 'Santolina viridis (Santoline verte)', 'img\\imgBDD\\Santolineverte.png', 'blanc ivoire', 'vert profond', 1, 1, 'juin', NULL, 'persistant', 'soleil', 'drainé, pauvre, calcaire', 'boule régulière', NULL, NULL, 'massif, jardin sur gravier', 'effectuer une taille de rajeunissement au printemps.', NULL, 'le feuillage dégage une agréable odeur d’huile d’olive', ''),
(222, 'vivace', 'Festuca glauca \'Elijah Blue\' (Fétuque bleue)', 'img\\imgBDD\\Fetuquebleue2.png', 'jaune', 'bleuté', 0, 0, 'mai-juillet', NULL, 'persistant', NULL, 'sec, drainé, supporte le calcaire', 'touffe buissonnante', NULL, NULL, 'rocaille, jardin sur gravier, petit couvre-sol', 'Tondre pas trop bas ou tailler les parties sèches avant le démarrage de la végétation au printemps. Le coloris sera plus intense et la longévité sera favorisée. Si la touffe se dégarnit au centre, diviser puis replanter au début du printemps.', NULL, 'une des fétuques bleues les plus résistantes', ''),
(223, 'vivace', 'PHLOMIS \'Edward Bowles\' (Sauge en arbre)', 'img\\imgBDD\\Saugeenarbre.png', 'jaune', 'vert', 1, 1, 'juin-août', NULL, 'persistant', 'soleil', 'sec, profond, drainé, supporte le calcaire', 'touffe buissonnante', NULL, NULL, 'massif de vivaces et d’arbustes, couvre-sol allélopathique', 'tailler dès que les graines ne sont plus décoratives pour arrondir la touffe et la garder compacte. Éliminer en hiver les tiges en surnombre.', NULL, 'apporte en hiver une décoration très \'graphique\' par ses graines qui deviennent presque noires en séchant.', ''),
(224, 'vivace', 'Santolina Etrusca (Santoline des Etrusques)', 'img\\imgBDD\\SantolinedesEtrusques.png', 'blanc crème', 'gris-vert', 0, 1, 'printemps', NULL, 'persistant', 'soleil', 'drainé, léger, calcaire', 'touffe arrondie', NULL, NULL, 'massif, jardin sur gravier', 'effectuer une taille de rajeunissement au printemps.', NULL, NULL, ''),
(225, 'vivace', 'Campanula portenschlagiana (Campanule des murs)', 'img\\imgBDD\\Campanulemurs.png', 'bleu', 'vert', 0, 0, 'juin-septembre', NULL, 'persistant', 'soleil, mi-ombre', 'pas trop sec à frais', 'tapissante, couvre-sol', NULL, NULL, 'bordures, rocaille, muret', 'Tailler en petites touffes courtes dès la fanaison; une nouvelle végétation et de belles floraisons se renouvelleront rapidement. Nettoyer la touffe en fin d\'hiver.', NULL, NULL, ''),
(226, 'vivace', 'Arctanthemum arcticum (Chrysanthème arctique)', 'img\\imgBDD\\Chrysanthemearctique.png', 'blanc rosé', 'vert', 0, 1, 'août-octobre', NULL, 'caduc ou semi-persistant', 'soleil, mi-ombre', 'tous, supporte calcaire', 'touffe étalée', NULL, NULL, 'bac, rocaille, jardin sur gravier. Couvre-sol', 'Supprimer les fleurs fanées pour prolonger les floraisons. Rabattre la touffe dès qu\'elle n\'est plus décorative et au plus tard en fin d\'hiver.', NULL, NULL, ''),
(227, 'vivace', 'Miscanthus transmorrisonensis (Roseau de Chine)', 'img\\imgBDD\\RoseauChine.png', 'rose', 'vert', 2, 2, 'août-novembre', NULL, 'persistant', 'soleil', 'frais et humide', 'touffe hérissée', NULL, NULL, 'isolé ou fond de massif', 'éliminer les tiges pliées ou abîmées en fin d\'automne, les chaumes robustes restants donneront le relief et le graphisme aux massifs pendant l\'hiver et se décoreront les jours de givre. Rabattre la touffe au démarrage de la végétation en début de printemps.', NULL, NULL, ''),
(228, 'vivace', 'Achillea ptarmica (Achilléen ptarmique)', 'img\\imgBDD\\Achilleenptarmique.png', 'blanc', 'vert', 1, NULL, 'juillet à septembre', NULL, 'caduc', 'soleil, mi-ombre', 'frais et humifère', 'touffe érigée', NULL, NULL, 'massif de vivaces', 'couper les tiges florales fanées à la base pour prolonger les floraisons. Rabattre la touffe sèche dès qu\'elle n\'est plus décorative.', NULL, 'nectarifère, attire les papillons et abeilles', ''),
(229, 'vivace', 'Geranium cantabrigiense \'Karmina\' (Géranium vivace)', 'img\\imgBDD\\Geraniumvivace.png', 'rose carmin', 'vert', 0, 1, 'mai-juillet', NULL, 'persistant', 'soleil, mi-ombre', 'sec et frais', 'touffe étalée', NULL, NULL, 'couvre-sol', 'pratiquement sans entretien. Nettoyer les parties sèches après floraison et en fin d\'hiver. ', NULL, NULL, ''),
(230, 'vivace', 'Tanacetum vulgare (Tanaisie)', 'img\\imgBDD\\Tanaisie.png', 'jaune', 'vert', 1, NULL, 'juillet-septembre', NULL, 'caduc', 'soleil', 'frais et humide', 'touffe dressée', NULL, NULL, 'la tanaisie éloigne de nombreux insectes. On l’utilise sous différentes formes : macération, infusion, décoction et purin', 'couper les inflorescences après floraison en réduisant un peu le feuillage. Rabattre dès que le feuillage sec n\'est plus décoratif.', NULL, NULL, ''),
(231, 'vivace', 'Tanacetum densum subsp amanii (Tanaisie d\'Arménie)', 'img\\imgBDD\\TanaisieArmenie.png', 'jaune', 'blanc argenté', 0, 0, 'juin-juillet', NULL, 'persistant', 'soleil, mi-ombre', 'pauvre, drainé, supporte le calcaire', 'couvre-sol', NULL, NULL, 'rocaille, dallage, couvre-sol allélopathique, jardin sur gravier', NULL, NULL, 'supporte bien la concurrence racinaire au pied des arbres et arbustes à feuilles caduques.', ''),
(232, 'vivace', 'Liriope muscari', 'img\\imgBDD\\Liriopemuscari.png', 'violet', 'vert', 0, 0, 'juillet-octobre', NULL, 'persistant', 'mi-ombre, ombre', 'sec et frais, humifère', 'touffe arrondie', NULL, NULL, 'couvre-sol sous les arbres', 'Pratiquement sans entretien. Nettoyer la touffe, si nécessaire, en fin d\'hiver.', NULL, NULL, ''),
(233, 'vivace', 'Sauge Californienne', 'img\\imgBDD\\Salviabeesbliss.png', 'bleu violet', 'gris argenté', 0.3, 0.8, 'été', NULL, 'persistant', 'soleil', 'drainé, pauvre, sec, calcaire', 'touffe étalée', NULL, '-11°C', 'couvre-sol, jardin sur gravier, mixed-border', 'Supprimer le bois mort, ou taille de formation  après le redémarrage de la végétation. Privilégier un paillage minéral.', NULL, 'fleurs comestibles, mellifère, feuillage odorant', 'Salvia Bee\'s Bliss');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `plante`
--
ALTER TABLE `plante`
  ADD PRIMARY KEY (`idPlante`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `plante`
--
ALTER TABLE `plante`
  MODIFY `idPlante` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=234;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
